for file in *
    do
        if [ "${file##*.}"x = "cl"x ];then
             if [[ "${file}" == gemm_nt.cl ]];then
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_130.bin  --options=\"${copt} -D LM=1 -D LN=3 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_140.bin  --options=\"${copt} -D LM=1 -D LN=4 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_150.bin  --options=\"${copt} -D LM=1 -D LN=5 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_160.bin  --options=\"${copt} -D LM=1 -D LN=6 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_170.bin  --options=\"${copt} -D LM=1 -D LN=7 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_180.bin  --options=\"${copt} -D LM=1 -D LN=8 -D LK=0 -D USE_V1 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_220.bin  --options=\"${copt} -D LM=2 -D LN=2 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_230.bin  --options=\"${copt} -D LM=2 -D LN=3 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_240.bin  --options=\"${copt} -D LM=2 -D LN=4 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_250.bin  --options=\"${copt} -D LM=2 -D LN=5 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_260.bin  --options=\"${copt} -D LM=2 -D LN=6 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_270.bin  --options=\"${copt} -D LM=2 -D LN=7 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_280.bin  --options=\"${copt} -D LM=2 -D LN=8 -D LK=0 -D USE_V1 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_310.bin  --options=\"${copt} -D LM=3 -D LN=1 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_320.bin  --options=\"${copt} -D LM=3 -D LN=2 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_330.bin  --options=\"${copt} -D LM=3 -D LN=3 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_340.bin  --options=\"${copt} -D LM=3 -D LN=4 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_350.bin  --options=\"${copt} -D LM=3 -D LN=5 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_360.bin  --options=\"${copt} -D LM=3 -D LN=6 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_370.bin  --options=\"${copt} -D LM=3 -D LN=7 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_380.bin  --options=\"${copt} -D LM=3 -D LN=8 -D LK=0 -D USE_V1 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_410.bin  --options=\"${copt} -D LM=4 -D LN=1 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_420.bin  --options=\"${copt} -D LM=4 -D LN=2 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_430.bin  --options=\"${copt} -D LM=4 -D LN=3 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_440.bin  --options=\"${copt} -D LM=4 -D LN=4 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_450.bin  --options=\"${copt} -D LM=4 -D LN=5 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_460.bin  --options=\"${copt} -D LM=4 -D LN=6 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_470.bin  --options=\"${copt} -D LM=4 -D LN=7 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_480.bin  --options=\"${copt} -D LM=4 -D LN=8 -D LK=0 -D USE_V1 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_510.bin  --options=\"${copt} -D LM=5 -D LN=1 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_520.bin  --options=\"${copt} -D LM=5 -D LN=2 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_530.bin  --options=\"${copt} -D LM=5 -D LN=3 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_540.bin  --options=\"${copt} -D LM=5 -D LN=4 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_550.bin  --options=\"${copt} -D LM=5 -D LN=5 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_560.bin  --options=\"${copt} -D LM=5 -D LN=6 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_570.bin  --options=\"${copt} -D LM=5 -D LN=7 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_580.bin  --options=\"${copt} -D LM=5 -D LN=8 -D LK=0 -D USE_V1 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_610.bin  --options=\"${copt} -D LM=6 -D LN=1 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_620.bin  --options=\"${copt} -D LM=6 -D LN=2 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_630.bin  --options=\"${copt} -D LM=6 -D LN=3 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_640.bin  --options=\"${copt} -D LM=6 -D LN=4 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_650.bin  --options=\"${copt} -D LM=6 -D LN=5 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_660.bin  --options=\"${copt} -D LM=6 -D LN=6 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_670.bin  --options=\"${copt} -D LM=6 -D LN=7 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_680.bin  --options=\"${copt} -D LM=6 -D LN=8 -D LK=0 -D USE_V1 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_710.bin  --options=\"${copt} -D LM=7 -D LN=1 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_720.bin  --options=\"${copt} -D LM=7 -D LN=2 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_730.bin  --options=\"${copt} -D LM=7 -D LN=3 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_740.bin  --options=\"${copt} -D LM=7 -D LN=4 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_750.bin  --options=\"${copt} -D LM=7 -D LN=5 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_760.bin  --options=\"${copt} -D LM=7 -D LN=6 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_770.bin  --options=\"${copt} -D LM=7 -D LN=7 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_780.bin  --options=\"${copt} -D LM=7 -D LN=8 -D LK=0 -D USE_V1 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_810.bin  --options=\"${copt} -D LM=8 -D LN=1 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_820.bin  --options=\"${copt} -D LM=8 -D LN=2 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_830.bin  --options=\"${copt} -D LM=8 -D LN=3 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_840.bin  --options=\"${copt} -D LM=8 -D LN=4 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_850.bin  --options=\"${copt} -D LM=8 -D LN=5 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_860.bin  --options=\"${copt} -D LM=8 -D LN=6 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_870.bin  --options=\"${copt} -D LM=8 -D LN=7 -D LK=0 -D USE_V1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_880.bin  --options=\"${copt} -D LM=8 -D LN=8 -D LK=0 -D USE_V1 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_131.bin  --options=\"${copt} -D LM=1 -D LN=3 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_141.bin  --options=\"${copt} -D LM=1 -D LN=4 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_151.bin  --options=\"${copt} -D LM=1 -D LN=5 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_161.bin  --options=\"${copt} -D LM=1 -D LN=6 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_171.bin  --options=\"${copt} -D LM=1 -D LN=7 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_181.bin  --options=\"${copt} -D LM=1 -D LN=8 -D LK=1 -D USE_V2 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_221.bin  --options=\"${copt} -D LM=2 -D LN=2 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_231.bin  --options=\"${copt} -D LM=2 -D LN=3 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_241.bin  --options=\"${copt} -D LM=2 -D LN=4 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_251.bin  --options=\"${copt} -D LM=2 -D LN=5 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_261.bin  --options=\"${copt} -D LM=2 -D LN=6 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_271.bin  --options=\"${copt} -D LM=2 -D LN=7 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_281.bin  --options=\"${copt} -D LM=2 -D LN=8 -D LK=1 -D USE_V2 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_311.bin  --options=\"${copt} -D LM=3 -D LN=1 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_321.bin  --options=\"${copt} -D LM=3 -D LN=2 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_331.bin  --options=\"${copt} -D LM=3 -D LN=3 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_341.bin  --options=\"${copt} -D LM=3 -D LN=4 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_351.bin  --options=\"${copt} -D LM=3 -D LN=5 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_361.bin  --options=\"${copt} -D LM=3 -D LN=6 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_371.bin  --options=\"${copt} -D LM=3 -D LN=7 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_381.bin  --options=\"${copt} -D LM=3 -D LN=8 -D LK=1 -D USE_V2 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_411.bin  --options=\"${copt} -D LM=4 -D LN=1 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_421.bin  --options=\"${copt} -D LM=4 -D LN=2 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_431.bin  --options=\"${copt} -D LM=4 -D LN=3 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_441.bin  --options=\"${copt} -D LM=4 -D LN=4 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_451.bin  --options=\"${copt} -D LM=4 -D LN=5 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_461.bin  --options=\"${copt} -D LM=4 -D LN=6 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_471.bin  --options=\"${copt} -D LM=4 -D LN=7 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_481.bin  --options=\"${copt} -D LM=4 -D LN=8 -D LK=1 -D USE_V2 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_511.bin  --options=\"${copt} -D LM=5 -D LN=1 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_521.bin  --options=\"${copt} -D LM=5 -D LN=2 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_531.bin  --options=\"${copt} -D LM=5 -D LN=3 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_541.bin  --options=\"${copt} -D LM=5 -D LN=4 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_551.bin  --options=\"${copt} -D LM=5 -D LN=5 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_561.bin  --options=\"${copt} -D LM=5 -D LN=6 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_571.bin  --options=\"${copt} -D LM=5 -D LN=7 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_581.bin  --options=\"${copt} -D LM=5 -D LN=8 -D LK=1 -D USE_V2 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_611.bin  --options=\"${copt} -D LM=6 -D LN=1 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_621.bin  --options=\"${copt} -D LM=6 -D LN=2 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_631.bin  --options=\"${copt} -D LM=6 -D LN=3 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_641.bin  --options=\"${copt} -D LM=6 -D LN=4 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_651.bin  --options=\"${copt} -D LM=6 -D LN=5 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_661.bin  --options=\"${copt} -D LM=6 -D LN=6 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_671.bin  --options=\"${copt} -D LM=6 -D LN=7 -D LK=1 -D USE_V2 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_711.bin  --options=\"${copt} -D LM=7 -D LN=1 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_721.bin  --options=\"${copt} -D LM=7 -D LN=2 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_731.bin  --options=\"${copt} -D LM=7 -D LN=3 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_741.bin  --options=\"${copt} -D LM=7 -D LN=4 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_751.bin  --options=\"${copt} -D LM=7 -D LN=5 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_761.bin  --options=\"${copt} -D LM=7 -D LN=6 -D LK=1 -D USE_V2 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_811.bin  --options=\"${copt} -D LM=8 -D LN=1 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_821.bin  --options=\"${copt} -D LM=8 -D LN=2 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_831.bin  --options=\"${copt} -D LM=8 -D LN=3 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_841.bin  --options=\"${copt} -D LM=8 -D LN=4 -D LK=1 -D USE_V2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_851.bin  --options=\"${copt} -D LM=8 -D LN=5 -D LK=1 -D USE_V2 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_132.bin  --options=\"${copt} -D LM=1 -D LN=3 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_142.bin  --options=\"${copt} -D LM=1 -D LN=4 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_152.bin  --options=\"${copt} -D LM=1 -D LN=5 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_162.bin  --options=\"${copt} -D LM=1 -D LN=6 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_172.bin  --options=\"${copt} -D LM=1 -D LN=7 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_182.bin  --options=\"${copt} -D LM=1 -D LN=8 -D LK=2 -D USE_V4 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_222.bin  --options=\"${copt} -D LM=2 -D LN=2 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_232.bin  --options=\"${copt} -D LM=2 -D LN=3 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_242.bin  --options=\"${copt} -D LM=2 -D LN=4 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_252.bin  --options=\"${copt} -D LM=2 -D LN=5 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_262.bin  --options=\"${copt} -D LM=2 -D LN=6 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_272.bin  --options=\"${copt} -D LM=2 -D LN=7 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_282.bin  --options=\"${copt} -D LM=2 -D LN=8 -D LK=2 -D USE_V4 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_312.bin  --options=\"${copt} -D LM=3 -D LN=1 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_322.bin  --options=\"${copt} -D LM=3 -D LN=2 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_332.bin  --options=\"${copt} -D LM=3 -D LN=3 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_342.bin  --options=\"${copt} -D LM=3 -D LN=4 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_352.bin  --options=\"${copt} -D LM=3 -D LN=5 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_362.bin  --options=\"${copt} -D LM=3 -D LN=6 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_372.bin  --options=\"${copt} -D LM=3 -D LN=7 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_382.bin  --options=\"${copt} -D LM=3 -D LN=8 -D LK=2 -D USE_V4 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_412.bin  --options=\"${copt} -D LM=4 -D LN=1 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_422.bin  --options=\"${copt} -D LM=4 -D LN=2 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_432.bin  --options=\"${copt} -D LM=4 -D LN=3 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_442.bin  --options=\"${copt} -D LM=4 -D LN=4 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_452.bin  --options=\"${copt} -D LM=4 -D LN=5 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_462.bin  --options=\"${copt} -D LM=4 -D LN=6 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_472.bin  --options=\"${copt} -D LM=4 -D LN=7 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_482.bin  --options=\"${copt} -D LM=4 -D LN=8 -D LK=2 -D USE_V4 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_512.bin  --options=\"${copt} -D LM=5 -D LN=1 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_522.bin  --options=\"${copt} -D LM=5 -D LN=2 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_532.bin  --options=\"${copt} -D LM=5 -D LN=3 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_542.bin  --options=\"${copt} -D LM=5 -D LN=4 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_552.bin  --options=\"${copt} -D LM=5 -D LN=5 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_562.bin  --options=\"${copt} -D LM=5 -D LN=6 -D LK=2 -D USE_V4 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_612.bin  --options=\"${copt} -D LM=6 -D LN=1 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_622.bin  --options=\"${copt} -D LM=6 -D LN=2 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_632.bin  --options=\"${copt} -D LM=6 -D LN=3 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_642.bin  --options=\"${copt} -D LM=6 -D LN=4 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_652.bin  --options=\"${copt} -D LM=6 -D LN=5 -D LK=2 -D USE_V4 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_712.bin  --options=\"${copt} -D LM=7 -D LN=1 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_722.bin  --options=\"${copt} -D LM=7 -D LN=2 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_732.bin  --options=\"${copt} -D LM=7 -D LN=3 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_742.bin  --options=\"${copt} -D LM=7 -D LN=4 -D LK=2 -D USE_V4 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_812.bin  --options=\"${copt} -D LM=8 -D LN=1 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_822.bin  --options=\"${copt} -D LM=8 -D LN=2 -D LK=2 -D USE_V4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_832.bin  --options=\"${copt} -D LM=8 -D LN=3 -D LK=2 -D USE_V4 -D NO_BIAS\"
             fi
        fi
    done



