for file in *
    do
        if [ "${file##*.}"x = "cl"x ];then
             if [[ "${file}" == gemm_tn.cl ]];then
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_41.bin  --options=\"${copt} -D LM=4 -D LN=1 -D UN=0 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_42.bin  --options=\"${copt} -D LM=4 -D LN=2 -D UN=1 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_43.bin  --options=\"${copt} -D LM=4 -D LN=3 -D UN=2 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_44.bin  --options=\"${copt} -D LM=4 -D LN=4 -D UN=3 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_45.bin  --options=\"${copt} -D LM=4 -D LN=5 -D UN=4 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_46.bin  --options=\"${copt} -D LM=4 -D LN=6 -D UN=5 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_47.bin  --options=\"${copt} -D LM=4 -D LN=7 -D UN=6 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_48.bin  --options=\"${copt} -D LM=4 -D LN=8 -D UN=7 -DUSE_NCWHC4\"

                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_81.bin  --options=\"${copt} -D LM=8 -D LN=1 -D UN=0 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_82.bin  --options=\"${copt} -D LM=8 -D LN=2 -D UN=1 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_83.bin  --options=\"${copt} -D LM=8 -D LN=3 -D UN=2 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_84.bin  --options=\"${copt} -D LM=8 -D LN=4 -D UN=3 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_85.bin  --options=\"${copt} -D LM=8 -D LN=5 -D UN=4 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_86.bin  --options=\"${copt} -D LM=8 -D LN=6 -D UN=5 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_87.bin  --options=\"${copt} -D LM=8 -D LN=7 -D UN=6 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_88.bin  --options=\"${copt} -D LM=8 -D LN=8 -D UN=7 -DUSE_NCWHC4\"

                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_41.bin  --options=\"${copt} -D LM=4 -D LN=1 -D UN=0 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_42.bin  --options=\"${copt} -D LM=4 -D LN=2 -D UN=1 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_43.bin  --options=\"${copt} -D LM=4 -D LN=3 -D UN=2 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_44.bin  --options=\"${copt} -D LM=4 -D LN=4 -D UN=3 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_45.bin  --options=\"${copt} -D LM=4 -D LN=5 -D UN=4 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_46.bin  --options=\"${copt} -D LM=4 -D LN=6 -D UN=5 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_47.bin  --options=\"${copt} -D LM=4 -D LN=7 -D UN=6 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_48.bin  --options=\"${copt} -D LM=4 -D LN=8 -D UN=7 -DUSE_NCWHC4 -DUSE_RELU\"

                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_81.bin  --options=\"${copt} -D LM=8 -D LN=1 -D UN=0 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_82.bin  --options=\"${copt} -D LM=8 -D LN=2 -D UN=1 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_83.bin  --options=\"${copt} -D LM=8 -D LN=3 -D UN=2 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_84.bin  --options=\"${copt} -D LM=8 -D LN=4 -D UN=3 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_85.bin  --options=\"${copt} -D LM=8 -D LN=5 -D UN=4 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_86.bin  --options=\"${copt} -D LM=8 -D LN=6 -D UN=5 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_87.bin  --options=\"${copt} -D LM=8 -D LN=7 -D UN=6 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_88.bin  --options=\"${copt} -D LM=8 -D LN=8 -D UN=7 -DUSE_NCWHC4 -DUSE_RELU\"

#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_41.bin  --options=\"${copt} -D LM=4 -D LN=1 -D UN=0 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_42.bin  --options=\"${copt} -D LM=4 -D LN=2 -D UN=1 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_43.bin  --options=\"${copt} -D LM=4 -D LN=3 -D UN=2 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_44.bin  --options=\"${copt} -D LM=4 -D LN=4 -D UN=3 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_45.bin  --options=\"${copt} -D LM=4 -D LN=5 -D UN=4 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_46.bin  --options=\"${copt} -D LM=4 -D LN=6 -D UN=5 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_47.bin  --options=\"${copt} -D LM=4 -D LN=7 -D UN=6 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_48.bin  --options=\"${copt} -D LM=4 -D LN=8 -D UN=7 -DUSE_NCWHC4 -DUSE_GELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_81.bin  --options=\"${copt} -D LM=8 -D LN=1 -D UN=0 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_82.bin  --options=\"${copt} -D LM=8 -D LN=2 -D UN=1 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_83.bin  --options=\"${copt} -D LM=8 -D LN=3 -D UN=2 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_84.bin  --options=\"${copt} -D LM=8 -D LN=4 -D UN=3 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_85.bin  --options=\"${copt} -D LM=8 -D LN=5 -D UN=4 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_86.bin  --options=\"${copt} -D LM=8 -D LN=6 -D UN=5 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_87.bin  --options=\"${copt} -D LM=8 -D LN=7 -D UN=6 -DUSE_NCWHC4 -DUSE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_ncwhc4_88.bin  --options=\"${copt} -D LM=8 -D LN=8 -D UN=7 -DUSE_NCWHC4 -DUSE_GELU\"

                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_41.bin  --options=\"${copt} -D LM=4 -D LN=1 -D UN=0 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_42.bin  --options=\"${copt} -D LM=4 -D LN=2 -D UN=1 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_43.bin  --options=\"${copt} -D LM=4 -D LN=3 -D UN=2 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_44.bin  --options=\"${copt} -D LM=4 -D LN=4 -D UN=3 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_45.bin  --options=\"${copt} -D LM=4 -D LN=5 -D UN=4 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_46.bin  --options=\"${copt} -D LM=4 -D LN=6 -D UN=5 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_47.bin  --options=\"${copt} -D LM=4 -D LN=7 -D UN=6 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_48.bin  --options=\"${copt} -D LM=4 -D LN=8 -D UN=7 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"

                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_81.bin  --options=\"${copt} -D LM=8 -D LN=1 -D UN=0 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_82.bin  --options=\"${copt} -D LM=8 -D LN=2 -D UN=1 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_83.bin  --options=\"${copt} -D LM=8 -D LN=3 -D UN=2 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_84.bin  --options=\"${copt} -D LM=8 -D LN=4 -D UN=3 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_85.bin  --options=\"${copt} -D LM=8 -D LN=5 -D UN=4 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_86.bin  --options=\"${copt} -D LM=8 -D LN=6 -D UN=5 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_87.bin  --options=\"${copt} -D LM=8 -D LN=7 -D UN=6 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise1_ncwhc4_88.bin  --options=\"${copt} -D LM=8 -D LN=8 -D UN=7 -DUSE_NCWHC4 -DUSE_ELTWISE_NCHW\"

                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_41.bin  --options=\"${copt} -D LM=4 -D LN=1 -D UN=0 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_42.bin  --options=\"${copt} -D LM=4 -D LN=2 -D UN=1 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_43.bin  --options=\"${copt} -D LM=4 -D LN=3 -D UN=2 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_44.bin  --options=\"${copt} -D LM=4 -D LN=4 -D UN=3 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_45.bin  --options=\"${copt} -D LM=4 -D LN=5 -D UN=4 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_46.bin  --options=\"${copt} -D LM=4 -D LN=6 -D UN=5 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_47.bin  --options=\"${copt} -D LM=4 -D LN=7 -D UN=6 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_48.bin  --options=\"${copt} -D LM=4 -D LN=8 -D UN=7 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"

                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_81.bin  --options=\"${copt} -D LM=8 -D LN=1 -D UN=0 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_82.bin  --options=\"${copt} -D LM=8 -D LN=2 -D UN=1 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_83.bin  --options=\"${copt} -D LM=8 -D LN=3 -D UN=2 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_84.bin  --options=\"${copt} -D LM=8 -D LN=4 -D UN=3 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_85.bin  --options=\"${copt} -D LM=8 -D LN=5 -D UN=4 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_86.bin  --options=\"${copt} -D LM=8 -D LN=6 -D UN=5 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_87.bin  --options=\"${copt} -D LM=8 -D LN=7 -D UN=6 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_eltwise4_ncwhc4_88.bin  --options=\"${copt} -D LM=8 -D LN=8 -D UN=7 -DUSE_NCWHC4 -DUSE_ELTWISE_NCWHC4\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_13.bin  --options=\"${copt} -D LM=1 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_14.bin  --options=\"${copt} -D LM=1 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_15.bin  --options=\"${copt} -D LM=1 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_16.bin  --options=\"${copt} -D LM=1 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_17.bin  --options=\"${copt} -D LM=1 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_18.bin  --options=\"${copt} -D LM=1 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_22.bin  --options=\"${copt} -D LM=2 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_23.bin  --options=\"${copt} -D LM=2 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_24.bin  --options=\"${copt} -D LM=2 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_25.bin  --options=\"${copt} -D LM=2 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_26.bin  --options=\"${copt} -D LM=2 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_27.bin  --options=\"${copt} -D LM=2 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_28.bin  --options=\"${copt} -D LM=2 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_31.bin  --options=\"${copt} -D LM=3 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_32.bin  --options=\"${copt} -D LM=3 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_33.bin  --options=\"${copt} -D LM=3 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_34.bin  --options=\"${copt} -D LM=3 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_35.bin  --options=\"${copt} -D LM=3 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_36.bin  --options=\"${copt} -D LM=3 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_37.bin  --options=\"${copt} -D LM=3 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_38.bin  --options=\"${copt} -D LM=3 -D LN=8 -D NO_BIAS\"
                
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_41.bin  --options=\"${copt} -D LM=4 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_42.bin  --options=\"${copt} -D LM=4 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_43.bin  --options=\"${copt} -D LM=4 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_44.bin  --options=\"${copt} -D LM=4 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_45.bin  --options=\"${copt} -D LM=4 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_46.bin  --options=\"${copt} -D LM=4 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_47.bin  --options=\"${copt} -D LM=4 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_48.bin  --options=\"${copt} -D LM=4 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_51.bin  --options=\"${copt} -D LM=5 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_52.bin  --options=\"${copt} -D LM=5 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_53.bin  --options=\"${copt} -D LM=5 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_54.bin  --options=\"${copt} -D LM=5 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_55.bin  --options=\"${copt} -D LM=5 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_56.bin  --options=\"${copt} -D LM=5 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_57.bin  --options=\"${copt} -D LM=5 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_58.bin  --options=\"${copt} -D LM=5 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_61.bin  --options=\"${copt} -D LM=6 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_62.bin  --options=\"${copt} -D LM=6 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_63.bin  --options=\"${copt} -D LM=6 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_64.bin  --options=\"${copt} -D LM=6 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_65.bin  --options=\"${copt} -D LM=6 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_66.bin  --options=\"${copt} -D LM=6 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_67.bin  --options=\"${copt} -D LM=6 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_68.bin  --options=\"${copt} -D LM=6 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_71.bin  --options=\"${copt} -D LM=7 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_72.bin  --options=\"${copt} -D LM=7 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_73.bin  --options=\"${copt} -D LM=7 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_74.bin  --options=\"${copt} -D LM=7 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_75.bin  --options=\"${copt} -D LM=7 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_76.bin  --options=\"${copt} -D LM=7 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_77.bin  --options=\"${copt} -D LM=7 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_78.bin  --options=\"${copt} -D LM=7 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_81.bin  --options=\"${copt} -D LM=8 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_82.bin  --options=\"${copt} -D LM=8 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_83.bin  --options=\"${copt} -D LM=8 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_84.bin  --options=\"${copt} -D LM=8 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_85.bin  --options=\"${copt} -D LM=8 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_86.bin  --options=\"${copt} -D LM=8 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_87.bin  --options=\"${copt} -D LM=8 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_88.bin  --options=\"${copt} -D LM=8 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_13.bin  --options=\"${copt} -D LM=1 -D LN=3\"
                echo ./gcl_binary --input=$file --output=${file%.*}_14.bin  --options=\"${copt} -D LM=1 -D LN=4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_15.bin  --options=\"${copt} -D LM=1 -D LN=5\"
                echo ./gcl_binary --input=$file --output=${file%.*}_16.bin  --options=\"${copt} -D LM=1 -D LN=6\"
                echo ./gcl_binary --input=$file --output=${file%.*}_17.bin  --options=\"${copt} -D LM=1 -D LN=7\"
                echo ./gcl_binary --input=$file --output=${file%.*}_18.bin  --options=\"${copt} -D LM=1 -D LN=8\"

                echo ./gcl_binary --input=$file --output=${file%.*}_22.bin  --options=\"${copt} -D LM=2 -D LN=2\"
                echo ./gcl_binary --input=$file --output=${file%.*}_23.bin  --options=\"${copt} -D LM=2 -D LN=3\"
                echo ./gcl_binary --input=$file --output=${file%.*}_24.bin  --options=\"${copt} -D LM=2 -D LN=4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_25.bin  --options=\"${copt} -D LM=2 -D LN=5\"
                echo ./gcl_binary --input=$file --output=${file%.*}_26.bin  --options=\"${copt} -D LM=2 -D LN=6\"
                echo ./gcl_binary --input=$file --output=${file%.*}_27.bin  --options=\"${copt} -D LM=2 -D LN=7\"
                echo ./gcl_binary --input=$file --output=${file%.*}_28.bin  --options=\"${copt} -D LM=2 -D LN=8\"

                echo ./gcl_binary --input=$file --output=${file%.*}_31.bin  --options=\"${copt} -D LM=3 -D LN=1\"
                echo ./gcl_binary --input=$file --output=${file%.*}_32.bin  --options=\"${copt} -D LM=3 -D LN=2\"
                echo ./gcl_binary --input=$file --output=${file%.*}_33.bin  --options=\"${copt} -D LM=3 -D LN=3\"
                echo ./gcl_binary --input=$file --output=${file%.*}_34.bin  --options=\"${copt} -D LM=3 -D LN=4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_35.bin  --options=\"${copt} -D LM=3 -D LN=5\"
                echo ./gcl_binary --input=$file --output=${file%.*}_36.bin  --options=\"${copt} -D LM=3 -D LN=6\"
                echo ./gcl_binary --input=$file --output=${file%.*}_37.bin  --options=\"${copt} -D LM=3 -D LN=7\"
                echo ./gcl_binary --input=$file --output=${file%.*}_38.bin  --options=\"${copt} -D LM=3 -D LN=8\"
                
                echo ./gcl_binary --input=$file --output=${file%.*}_41.bin  --options=\"${copt} -D LM=4 -D LN=1\"
                echo ./gcl_binary --input=$file --output=${file%.*}_42.bin  --options=\"${copt} -D LM=4 -D LN=2\"
                echo ./gcl_binary --input=$file --output=${file%.*}_43.bin  --options=\"${copt} -D LM=4 -D LN=3\"
                echo ./gcl_binary --input=$file --output=${file%.*}_44.bin  --options=\"${copt} -D LM=4 -D LN=4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_45.bin  --options=\"${copt} -D LM=4 -D LN=5\"
                echo ./gcl_binary --input=$file --output=${file%.*}_46.bin  --options=\"${copt} -D LM=4 -D LN=6\"
                echo ./gcl_binary --input=$file --output=${file%.*}_47.bin  --options=\"${copt} -D LM=4 -D LN=7\"
                echo ./gcl_binary --input=$file --output=${file%.*}_48.bin  --options=\"${copt} -D LM=4 -D LN=8\"

                echo ./gcl_binary --input=$file --output=${file%.*}_51.bin  --options=\"${copt} -D LM=5 -D LN=1\"
                echo ./gcl_binary --input=$file --output=${file%.*}_52.bin  --options=\"${copt} -D LM=5 -D LN=2\"
                echo ./gcl_binary --input=$file --output=${file%.*}_53.bin  --options=\"${copt} -D LM=5 -D LN=3\"
                echo ./gcl_binary --input=$file --output=${file%.*}_54.bin  --options=\"${copt} -D LM=5 -D LN=4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_55.bin  --options=\"${copt} -D LM=5 -D LN=5\"
                echo ./gcl_binary --input=$file --output=${file%.*}_56.bin  --options=\"${copt} -D LM=5 -D LN=6\"
                echo ./gcl_binary --input=$file --output=${file%.*}_57.bin  --options=\"${copt} -D LM=5 -D LN=7\"
                echo ./gcl_binary --input=$file --output=${file%.*}_58.bin  --options=\"${copt} -D LM=5 -D LN=8\"

                echo ./gcl_binary --input=$file --output=${file%.*}_61.bin  --options=\"${copt} -D LM=6 -D LN=1\"
                echo ./gcl_binary --input=$file --output=${file%.*}_62.bin  --options=\"${copt} -D LM=6 -D LN=2\"
                echo ./gcl_binary --input=$file --output=${file%.*}_63.bin  --options=\"${copt} -D LM=6 -D LN=3\"
                echo ./gcl_binary --input=$file --output=${file%.*}_64.bin  --options=\"${copt} -D LM=6 -D LN=4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_65.bin  --options=\"${copt} -D LM=6 -D LN=5\"
                echo ./gcl_binary --input=$file --output=${file%.*}_66.bin  --options=\"${copt} -D LM=6 -D LN=6\"
                echo ./gcl_binary --input=$file --output=${file%.*}_67.bin  --options=\"${copt} -D LM=6 -D LN=7\"
                echo ./gcl_binary --input=$file --output=${file%.*}_68.bin  --options=\"${copt} -D LM=6 -D LN=8\"

                echo ./gcl_binary --input=$file --output=${file%.*}_71.bin  --options=\"${copt} -D LM=7 -D LN=1\"
                echo ./gcl_binary --input=$file --output=${file%.*}_72.bin  --options=\"${copt} -D LM=7 -D LN=2\"
                echo ./gcl_binary --input=$file --output=${file%.*}_73.bin  --options=\"${copt} -D LM=7 -D LN=3\"
                echo ./gcl_binary --input=$file --output=${file%.*}_74.bin  --options=\"${copt} -D LM=7 -D LN=4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_75.bin  --options=\"${copt} -D LM=7 -D LN=5\"
                echo ./gcl_binary --input=$file --output=${file%.*}_76.bin  --options=\"${copt} -D LM=7 -D LN=6\"
                echo ./gcl_binary --input=$file --output=${file%.*}_77.bin  --options=\"${copt} -D LM=7 -D LN=7\"
                echo ./gcl_binary --input=$file --output=${file%.*}_78.bin  --options=\"${copt} -D LM=7 -D LN=8\"

                echo ./gcl_binary --input=$file --output=${file%.*}_81.bin  --options=\"${copt} -D LM=8 -D LN=1\"
                echo ./gcl_binary --input=$file --output=${file%.*}_82.bin  --options=\"${copt} -D LM=8 -D LN=2\"
                echo ./gcl_binary --input=$file --output=${file%.*}_83.bin  --options=\"${copt} -D LM=8 -D LN=3\"
                echo ./gcl_binary --input=$file --output=${file%.*}_84.bin  --options=\"${copt} -D LM=8 -D LN=4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_85.bin  --options=\"${copt} -D LM=8 -D LN=5\"
                echo ./gcl_binary --input=$file --output=${file%.*}_86.bin  --options=\"${copt} -D LM=8 -D LN=6\"
                echo ./gcl_binary --input=$file --output=${file%.*}_87.bin  --options=\"${copt} -D LM=8 -D LN=7\"
                echo ./gcl_binary --input=$file --output=${file%.*}_88.bin  --options=\"${copt} -D LM=8 -D LN=8\"

#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_13.bin  --options=\"${copt} -D LM=1 -D LN=3 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_14.bin  --options=\"${copt} -D LM=1 -D LN=4 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_15.bin  --options=\"${copt} -D LM=1 -D LN=5 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_16.bin  --options=\"${copt} -D LM=1 -D LN=6 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_17.bin  --options=\"${copt} -D LM=1 -D LN=7 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_18.bin  --options=\"${copt} -D LM=1 -D LN=8 -D USE_RELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_22.bin  --options=\"${copt} -D LM=2 -D LN=2 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_23.bin  --options=\"${copt} -D LM=2 -D LN=3 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_24.bin  --options=\"${copt} -D LM=2 -D LN=4 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_25.bin  --options=\"${copt} -D LM=2 -D LN=5 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_26.bin  --options=\"${copt} -D LM=2 -D LN=6 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_27.bin  --options=\"${copt} -D LM=2 -D LN=7 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_28.bin  --options=\"${copt} -D LM=2 -D LN=8 -D USE_RELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_31.bin  --options=\"${copt} -D LM=3 -D LN=1 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_32.bin  --options=\"${copt} -D LM=3 -D LN=2 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_33.bin  --options=\"${copt} -D LM=3 -D LN=3 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_34.bin  --options=\"${copt} -D LM=3 -D LN=4 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_35.bin  --options=\"${copt} -D LM=3 -D LN=5 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_36.bin  --options=\"${copt} -D LM=3 -D LN=6 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_37.bin  --options=\"${copt} -D LM=3 -D LN=7 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_38.bin  --options=\"${copt} -D LM=3 -D LN=8 -D USE_RELU\"
#                
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_41.bin  --options=\"${copt} -D LM=4 -D LN=1 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_42.bin  --options=\"${copt} -D LM=4 -D LN=2 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_43.bin  --options=\"${copt} -D LM=4 -D LN=3 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_44.bin  --options=\"${copt} -D LM=4 -D LN=4 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_45.bin  --options=\"${copt} -D LM=4 -D LN=5 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_46.bin  --options=\"${copt} -D LM=4 -D LN=6 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_47.bin  --options=\"${copt} -D LM=4 -D LN=7 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_48.bin  --options=\"${copt} -D LM=4 -D LN=8 -D USE_RELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_51.bin  --options=\"${copt} -D LM=5 -D LN=1 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_52.bin  --options=\"${copt} -D LM=5 -D LN=2 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_53.bin  --options=\"${copt} -D LM=5 -D LN=3 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_54.bin  --options=\"${copt} -D LM=5 -D LN=4 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_55.bin  --options=\"${copt} -D LM=5 -D LN=5 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_56.bin  --options=\"${copt} -D LM=5 -D LN=6 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_57.bin  --options=\"${copt} -D LM=5 -D LN=7 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_58.bin  --options=\"${copt} -D LM=5 -D LN=8 -D USE_RELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_61.bin  --options=\"${copt} -D LM=6 -D LN=1 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_62.bin  --options=\"${copt} -D LM=6 -D LN=2 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_63.bin  --options=\"${copt} -D LM=6 -D LN=3 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_64.bin  --options=\"${copt} -D LM=6 -D LN=4 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_65.bin  --options=\"${copt} -D LM=6 -D LN=5 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_66.bin  --options=\"${copt} -D LM=6 -D LN=6 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_67.bin  --options=\"${copt} -D LM=6 -D LN=7 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_68.bin  --options=\"${copt} -D LM=6 -D LN=8 -D USE_RELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_71.bin  --options=\"${copt} -D LM=7 -D LN=1 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_72.bin  --options=\"${copt} -D LM=7 -D LN=2 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_73.bin  --options=\"${copt} -D LM=7 -D LN=3 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_74.bin  --options=\"${copt} -D LM=7 -D LN=4 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_75.bin  --options=\"${copt} -D LM=7 -D LN=5 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_76.bin  --options=\"${copt} -D LM=7 -D LN=6 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_77.bin  --options=\"${copt} -D LM=7 -D LN=7 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_78.bin  --options=\"${copt} -D LM=7 -D LN=8 -D USE_RELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_81.bin  --options=\"${copt} -D LM=8 -D LN=1 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_82.bin  --options=\"${copt} -D LM=8 -D LN=2 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_83.bin  --options=\"${copt} -D LM=8 -D LN=3 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_84.bin  --options=\"${copt} -D LM=8 -D LN=4 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_85.bin  --options=\"${copt} -D LM=8 -D LN=5 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_86.bin  --options=\"${copt} -D LM=8 -D LN=6 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_87.bin  --options=\"${copt} -D LM=8 -D LN=7 -D USE_RELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_relu_88.bin  --options=\"${copt} -D LM=8 -D LN=8 -D USE_RELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_13.bin  --options=\"${copt} -D LM=1 -D LN=3 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_14.bin  --options=\"${copt} -D LM=1 -D LN=4 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_15.bin  --options=\"${copt} -D LM=1 -D LN=5 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_16.bin  --options=\"${copt} -D LM=1 -D LN=6 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_17.bin  --options=\"${copt} -D LM=1 -D LN=7 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_18.bin  --options=\"${copt} -D LM=1 -D LN=8 -D USE_GELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_22.bin  --options=\"${copt} -D LM=2 -D LN=2 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_23.bin  --options=\"${copt} -D LM=2 -D LN=3 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_24.bin  --options=\"${copt} -D LM=2 -D LN=4 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_25.bin  --options=\"${copt} -D LM=2 -D LN=5 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_26.bin  --options=\"${copt} -D LM=2 -D LN=6 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_27.bin  --options=\"${copt} -D LM=2 -D LN=7 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_28.bin  --options=\"${copt} -D LM=2 -D LN=8 -D USE_GELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_31.bin  --options=\"${copt} -D LM=3 -D LN=1 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_32.bin  --options=\"${copt} -D LM=3 -D LN=2 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_33.bin  --options=\"${copt} -D LM=3 -D LN=3 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_34.bin  --options=\"${copt} -D LM=3 -D LN=4 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_35.bin  --options=\"${copt} -D LM=3 -D LN=5 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_36.bin  --options=\"${copt} -D LM=3 -D LN=6 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_37.bin  --options=\"${copt} -D LM=3 -D LN=7 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_38.bin  --options=\"${copt} -D LM=3 -D LN=8 -D USE_GELU\"
#                
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_41.bin  --options=\"${copt} -D LM=4 -D LN=1 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_42.bin  --options=\"${copt} -D LM=4 -D LN=2 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_43.bin  --options=\"${copt} -D LM=4 -D LN=3 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_44.bin  --options=\"${copt} -D LM=4 -D LN=4 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_45.bin  --options=\"${copt} -D LM=4 -D LN=5 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_46.bin  --options=\"${copt} -D LM=4 -D LN=6 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_47.bin  --options=\"${copt} -D LM=4 -D LN=7 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_48.bin  --options=\"${copt} -D LM=4 -D LN=8 -D USE_GELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_51.bin  --options=\"${copt} -D LM=5 -D LN=1 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_52.bin  --options=\"${copt} -D LM=5 -D LN=2 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_53.bin  --options=\"${copt} -D LM=5 -D LN=3 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_54.bin  --options=\"${copt} -D LM=5 -D LN=4 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_55.bin  --options=\"${copt} -D LM=5 -D LN=5 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_56.bin  --options=\"${copt} -D LM=5 -D LN=6 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_57.bin  --options=\"${copt} -D LM=5 -D LN=7 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_58.bin  --options=\"${copt} -D LM=5 -D LN=8 -D USE_GELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_61.bin  --options=\"${copt} -D LM=6 -D LN=1 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_62.bin  --options=\"${copt} -D LM=6 -D LN=2 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_63.bin  --options=\"${copt} -D LM=6 -D LN=3 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_64.bin  --options=\"${copt} -D LM=6 -D LN=4 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_65.bin  --options=\"${copt} -D LM=6 -D LN=5 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_66.bin  --options=\"${copt} -D LM=6 -D LN=6 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_67.bin  --options=\"${copt} -D LM=6 -D LN=7 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_68.bin  --options=\"${copt} -D LM=6 -D LN=8 -D USE_GELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_71.bin  --options=\"${copt} -D LM=7 -D LN=1 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_72.bin  --options=\"${copt} -D LM=7 -D LN=2 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_73.bin  --options=\"${copt} -D LM=7 -D LN=3 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_74.bin  --options=\"${copt} -D LM=7 -D LN=4 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_75.bin  --options=\"${copt} -D LM=7 -D LN=5 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_76.bin  --options=\"${copt} -D LM=7 -D LN=6 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_77.bin  --options=\"${copt} -D LM=7 -D LN=7 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_78.bin  --options=\"${copt} -D LM=7 -D LN=8 -D USE_GELU\"
#
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_81.bin  --options=\"${copt} -D LM=8 -D LN=1 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_82.bin  --options=\"${copt} -D LM=8 -D LN=2 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_83.bin  --options=\"${copt} -D LM=8 -D LN=3 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_84.bin  --options=\"${copt} -D LM=8 -D LN=4 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_85.bin  --options=\"${copt} -D LM=8 -D LN=5 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_86.bin  --options=\"${copt} -D LM=8 -D LN=6 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_87.bin  --options=\"${copt} -D LM=8 -D LN=7 -D USE_GELU\"
#                echo ./gcl_binary --input=$file --output=${file%.*}_gelu_88.bin  --options=\"${copt} -D LM=8 -D LN=8 -D USE_GELU\"
             fi
        fi
    done



