# Copyright (C) 2021. Huawei Technologies Co., Ltd. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

cmake_minimum_required(VERSION 3.10...3.20 FATAL_ERROR)
target_sources(Raul PRIVATE
        training/network/WorkflowPoolGPU.h
        training/network/WorkflowPool.cpp
        training/network/NetworkParameters.cpp
        training/network/Workflow.h
        training/network/Workflow.cpp
        training/network/WorkflowEager.h
        training/network/WorkflowEager.cpp
        training/network/WorkflowActions.h
        training/network/WorkflowDB.cpp
        training/network/IntervalTree.h
        training/network/WorkflowDB.h
        training/network/IntervalTree.cpp
        training/network/WorkflowActions.cpp
        training/network/WorkflowPool.h
        training/network/NetworkParameters.h
        training/network/WorkflowPoolGPU.cpp
        training/network/Layers.h
        training/optimizers/Adadelta.cpp
        training/optimizers/Optimizer.h
        training/optimizers/LAMB.h
        training/optimizers/AdamW.h
        training/optimizers/AdamW.cpp
        training/optimizers/Adam.h
        training/optimizers/Ranger.cpp
        training/optimizers/Momentum.cpp
        training/optimizers/IOptimizer.h
        training/optimizers/Adagrad.h
        training/optimizers/Ranger.h
        training/optimizers/Optimizer.cpp
        training/optimizers/Adamax.h
        training/optimizers/Adamax.cpp
        training/optimizers/SGD.cpp
        training/optimizers/Adam.cpp
        training/optimizers/ASGD.h
        training/optimizers/SGD.h
        training/optimizers/Rprop.cpp
        training/optimizers/LAMB.cpp
        training/optimizers/Momentum.h
        training/optimizers/Adadelta.h
        training/optimizers/Nesterov.cpp
        training/optimizers/RMSprop.h
        training/optimizers/Adagrad.cpp
        training/optimizers/Nesterov.h
        training/optimizers/Rprop.h
        training/optimizers/RMSprop.cpp
        training/optimizers/regularizers/Regularizer.h
        training/optimizers/regularizers/strategies/L2.h
        training/optimizers/regularizers/strategies/L1.cpp
        training/optimizers/regularizers/strategies/IRegularizerStrategy.h
        training/optimizers/regularizers/strategies/L2.cpp
        training/optimizers/regularizers/strategies/L1.h
        training/optimizers/regularizers/Regularizer.cpp
        training/optimizers/ASGD.cpp
        training/optimizers/schedulers/LrScheduler.cpp
        training/optimizers/schedulers/LrScheduler.h
        training/optimizers/schedulers/strategies/Exponential.cpp
        training/optimizers/schedulers/strategies/StepOffset.cpp
        training/optimizers/schedulers/strategies/WarmUp.cpp
        training/optimizers/schedulers/strategies/ClipUpper.h
        training/optimizers/schedulers/strategies/WarmUp.h
        training/optimizers/schedulers/strategies/Lambda.h
        training/optimizers/schedulers/strategies/Base.cpp
        training/optimizers/schedulers/strategies/Base.h
        training/optimizers/schedulers/strategies/StepOffset.h
        training/optimizers/schedulers/strategies/Exponential.h
        training/optimizers/schedulers/strategies/Lambda.cpp
        training/optimizers/schedulers/strategies/ClipUpper.cpp
        training/optimizers/schedulers/strategies/ClipLower.cpp
        training/optimizers/schedulers/strategies/ClipLower.h
        training/opencl/kernels/raul_kernel_def.h
        training/opencl/kernels/kernel_def.h
        training/opencl/OpenclLoader.cpp
        training/opencl/OpenCLKernelManager.h
        training/opencl/OpenCLKernelManager.cpp
        training/opencl/GPUCommon.h
        training/opencl/GemmGPU.cpp
        training/opencl/GPUCommon.cpp
        training/opencl/GemmGPU.h
        training/opencl/CL/opencl.h
        training/opencl/CL/cl_egl.h
        training/opencl/CL/cl_gl.h
        training/opencl/CL/cl_ext.h
        training/opencl/CL/cl.h
        training/opencl/CL/cl_version.h
        training/opencl/CL/cl_platform.h
        training/opencl/CL/cl_gl_ext.h
        training/opencl/OpenclLoader.h
        training/tools/MNISTParser.cpp
        training/tools/MNISTParser.h
        training/tools/Datasets.h
        training/tools/Dataset.h
        training/optimizers/schedulers/strategies/CosineAnnealing.cpp
        training/optimizers/schedulers/strategies/CosineAnnealing.h
        training/tools/Profiler.h
        training/tools/CIFARParser.cpp
        training/tools/NamedTuple.h
        training/tools/DataTransformations.h
        training/tools/Profiler.cpp
        training/tools/NameGenerator.h
        training/tools/ElementSequence.cpp
        training/tools/Dataset.cpp
        training/tools/DataLoad.h
        training/tools/Utils.cpp
        training/tools/DataTransformations.cpp
        training/tools/Utils.h
        training/tools/DataLoad.cpp
        training/tools/Datasets.cpp
        training/tools/CIFARParser.h
        training/tools/ElementSequence.h
        training/postprocessing/GradientClipping.cpp
        training/postprocessing/GradientClipping.h
        training/postprocessing/GradientPostprocessor.h
        training/initializers/RandomUniformInitializer.cpp
        training/initializers/ConstantInitializer.cpp
        training/initializers/ConstantInitializer.h
        training/initializers/RandomNormInitializer.h
        training/initializers/XavierInitializer.h
        training/initializers/XavierInitializer.cpp
        training/initializers/RandomUniformInitializer.h
        training/initializers/IInitializer.h
        training/initializers/RandomNormInitializer.cpp
        training/common/Types.h
        training/common/Name.cpp
        training/common/TensorGPU.h
        training/common/OpenclInitializer.h
        training/common/MemoryManagerGPU.h
        training/common/TensorMem.h
        training/common/TypeHalf.h
        training/common/Test.cpp
        training/common/Conversions.h
        training/common/MemoryManager.cpp
        training/common/OpenCLInclude.h
        training/common/ExecutionProfile.h
        training/common/Test.h
        training/common/Train.cpp
        training/common/MemoryManager.h
        training/common/Random.cpp
        training/common/Errors.h
        training/common/Errors.cpp
        training/common/Common.h
        training/common/DataLoader.cpp
        training/common/Tensor.cpp
        training/common/Singleton.h
        training/common/Common.cpp
        training/common/vec_functions.h
        training/common/OpenclInitializer.cpp
        training/common/MemoryManagerGPU.cpp
        training/common/Tensor.h
        training/common/Name.h
        training/common/Random.h
        training/common/DataLoader.h
        training/common/TensorGPU.cpp
        training/common/Train.h
        training/common/quantization/SymmetricQuantizer.cpp
        training/common/quantization/IQuantizer.h
        training/common/quantization/AffineQuantizer.cpp
        training/common/quantization/AffineQuantizer.h
        training/common/quantization/SymmetricQuantizer.h
        training/common/io/TensorStream.h
        training/common/io/TensorStream.cpp
        training/layers/activations/ReLUActivation.h
        training/layers/activations/GeLUActivation.cpp
        training/layers/activations/HSwishActivation.h
        training/layers/activations/impl/ReLUActivationImpl.cpp
        training/layers/activations/impl/SoftPlusActivationGPU.cpp
        training/layers/activations/impl/SoftPlusActivationGPU.h
        training/layers/activations/impl/SoftPlusActivationCPU.cpp
        training/layers/activations/impl/ReLUActivationImpl.h
        training/layers/activations/impl/SoftPlusActivationCPU.h
        training/layers/activations/impl/SigmoidActivationCPU.cpp
        training/layers/activations/impl/SigmoidActivationCPU.h
        training/layers/activations/impl/SigmoidActivationGPU.cpp
        training/layers/activations/impl/SigmoidActivationGPU.h
        training/layers/activations/impl/TanhActivationCPU.cpp
        training/layers/activations/impl/TanhActivationCPU.h
        training/layers/activations/impl/TanhActivationGPU.cpp
        training/layers/activations/impl/TanhActivationGPU.h
        training/layers/activations/impl/SwishActivationCPU.cpp
        training/layers/activations/impl/SwishActivationCPU.h
        training/layers/activations/impl/SwishActivationGPU.cpp
        training/layers/activations/impl/SwishActivationGPU.h
        training/layers/activations/impl/SoftMaxActivationCPU.cpp
        training/layers/activations/impl/SoftMaxActivationCPU.h
        training/layers/activations/impl/SoftMaxActivationGPU.cpp
        training/layers/activations/impl/SoftMaxActivationGPU.h
        training/layers/activations/impl/LeakyReLUActivationCPU.cpp
        training/layers/activations/impl/LeakyReLUActivationCPU.h
        training/layers/activations/impl/GeLUActivationCPU.cpp
        training/layers/activations/impl/GeLUActivationCPU.h
        training/layers/activations/impl/GeLUActivationGPU.cpp
        training/layers/activations/impl/GeLUActivationGPU.h
        training/layers/activations/impl/HSigmoidActivationCPU.cpp
        training/layers/activations/impl/HSigmoidActivationCPU.h
        training/layers/activations/impl/HSigmoidActivationGPU.cpp
        training/layers/activations/impl/HSigmoidActivationGPU.h
        training/layers/activations/impl/HSwishActivationCPU.cpp
        training/layers/activations/impl/HSwishActivationCPU.h
        training/layers/activations/impl/HSwishActivationGPU.cpp
        training/layers/activations/impl/HSwishActivationGPU.h
        training/layers/activations/ReLUActivation.cpp
        training/layers/activations/HSigmoidActivation.h
        training/layers/activations/GeLUActivation.h
        training/layers/activations/SoftPlusActivation.h
        training/layers/activations/HSwishActivation.cpp
        training/layers/activations/LogSoftMaxActivation.cpp
        training/layers/activations/SoftPlusActivation.cpp
        training/layers/activations/SigmoidActivation.h
        training/layers/activations/SigmoidActivation.cpp
        training/layers/activations/LogSoftMaxActivation.h
        training/layers/activations/SoftMaxActivation.cpp
        training/layers/activations/SoftMaxActivation.h
        training/layers/activations/TanhActivation.h
        training/layers/activations/TanhActivation.cpp
        training/layers/activations/SwishActivation.h
        training/layers/activations/HSigmoidActivation.cpp
        training/layers/activations/SwishActivation.cpp
        training/layers/activations/LeakyReLUActivation.cpp
        training/layers/activations/LeakyReLUActivation.h
        training/layers/parameters/RandomTensorLayerParams.cpp
        training/layers/parameters/ZoneoutParams.cpp
        training/layers/parameters/TensorParams.h
        training/layers/parameters/TilingParameters.cpp
        training/layers/parameters/DataParams.cpp
        training/layers/parameters/ScaleParams.cpp
        training/layers/parameters/TilingParameters.h
        training/layers/parameters/GaussianUpsamplingParams.cpp
        training/layers/parameters/DropoutParams.cpp
        training/layers/parameters/RandomSelectParams.cpp
        training/layers/parameters/RollLayerParams.cpp
        training/layers/parameters/RandomChoiceParams.cpp
        training/layers/parameters/GaussianUpsamplingParams.h
        training/layers/parameters/FixedBiasParams.h
        training/layers/parameters/FixedBiasParams.cpp
        training/layers/parameters/SoftPlusActivationParams.cpp
        training/layers/parameters/trainable/TransformerParams.h
        training/layers/parameters/trainable/LocationSensitiveAttentionParams.cpp
        training/layers/parameters/trainable/LayerNormParams.h
        training/layers/parameters/trainable/BERTParams.h
        training/layers/parameters/trainable/TransposedConvolution2DParams.h
        training/layers/parameters/trainable/DynamicConvolutionAttentionParams.h
        training/layers/parameters/trainable/LSTMCellParams.cpp
        training/layers/parameters/trainable/LocationSensitiveAttentionParams.h
        training/layers/parameters/trainable/BatchnormParams.cpp
        training/layers/parameters/trainable/TransposedConvolution1DParams.h
        training/layers/parameters/trainable/DynamicConvolutionAttentionParams.cpp
        training/layers/parameters/trainable/TrainablePool2DParams.h
        training/layers/parameters/trainable/Convolution1DParams.cpp
        training/layers/parameters/trainable/TransformerParams.cpp
        training/layers/parameters/trainable/Convolution2DParams.cpp
        training/layers/parameters/trainable/MultiHeadAttentionParams.cpp
        training/layers/parameters/trainable/TacotronParams.cpp
        training/layers/parameters/trainable/LayerNormParams.cpp
        training/layers/parameters/trainable/TacotronParams.h
        training/layers/parameters/trainable/LSTMParams.h
        training/layers/parameters/trainable/TrainableParams.h
        training/layers/parameters/trainable/Convolution2DParams.h
        training/layers/parameters/trainable/LinearParams.h
        training/layers/parameters/trainable/LSTMParams.cpp
        training/layers/parameters/trainable/BatchnormParams.h
        training/layers/parameters/trainable/BahdanauAttentionParams.h
        training/layers/parameters/trainable/TransposedConvolution1DParams.cpp
        training/layers/parameters/trainable/EmbeddingParams.cpp
        training/layers/parameters/trainable/TransposedConvolution2DParams.cpp
        training/layers/parameters/trainable/BERTParams.cpp
        training/layers/parameters/trainable/MultiHeadAttentionParams.h
        training/layers/parameters/trainable/Convolution1DParams.h
        training/layers/parameters/trainable/LinearParams.cpp
        training/layers/parameters/trainable/BahdanauAttentionParams.cpp
        training/layers/parameters/trainable/LSTMCellParams.h
        training/layers/parameters/trainable/EmbeddingParams.h
        training/layers/parameters/trainable/TrainablePool2DParams.cpp
        training/layers/parameters/trainable/GRUCellParams.cpp
        training/layers/parameters/trainable/GRUCellParams.h
        training/layers/parameters/trainable/GRUParams.cpp
        training/layers/parameters/trainable/GRUParams.h
        training/layers/parameters/BasicParameters.cpp
        training/layers/parameters/FakeQuantParams.h
        training/layers/parameters/ZoneoutParams.h
        training/layers/parameters/RollLayerParams.h
        training/layers/parameters/DropoutParams.h
        training/layers/parameters/SlicingParams.cpp
        training/layers/parameters/ElementWiseComparisonLayerParams.h
        training/layers/parameters/IndexFillLayerParams.cpp
        training/layers/parameters/SoftPlusActivationParams.h
        training/layers/parameters/DataParams.h
        training/layers/parameters/RepeatInterleaveParams.h
        training/layers/parameters/ScaleParams.h
        training/layers/parameters/IndexFillLayerParams.h
        training/layers/parameters/LayerParameters.h
        training/layers/parameters/ClampLayerParams.cpp
        training/layers/parameters/RandomSelectParams.h
        training/layers/parameters/RepeatInterleaveParams.cpp
        training/layers/parameters/TensorParams.cpp
        training/layers/parameters/ClampLayerParams.h
        training/layers/parameters/ElementWiseComparisonLayerParams.cpp
        training/layers/parameters/RandomTensorLayerParams.h
        training/layers/parameters/SlicingParams.h
        training/layers/parameters/FakeQuantParams.cpp
        training/layers/parameters/BasicParameters.h
        training/layers/parameters/RandomChoiceParams.h
        training/layers/parameters/LeakyReLUParams.cpp
        training/layers/parameters/LeakyReLUParams.h
        training/layers/TrainableLayer.h
        training/layers/BroadcastingLayer.cpp
        training/layers/BroadcastingLayer.h
        training/layers/basic/ExpLayer.cpp
        training/layers/basic/DropoutLayer.h
        training/layers/basic/MatMulLayer.h
        training/layers/basic/ReshapeLayer.cpp
        training/layers/basic/BatchExpanderLayer.cpp
        training/layers/basic/ConcatenationLayer.h
        training/layers/basic/RandomTensorLayer.cpp
        training/layers/basic/FakeQuantLayer.cpp
        training/layers/basic/RoundLayer.h
        training/layers/basic/ReduceMeanLayer.cpp
        training/layers/basic/RandomTensorLayer.h
        training/layers/basic/RandomChoiceLayer.h
        training/layers/basic/ExpLayer.h
        training/layers/basic/ScaleLayer.h
        training/layers/basic/ScaleLayer.cpp
        training/layers/basic/MaxPoolLayer.h
        training/layers/basic/GlobalAveragePoolLayer.h
        training/layers/basic/ClampLayer.h
        training/layers/basic/ArgExtremumLayer.h
        training/layers/basic/PositionalEncoding.cpp
        training/layers/basic/SqrtLayer.h
        training/layers/basic/impl/DynamicDepthwiseConvolution2DLayerCPU.cpp
        training/layers/basic/impl/DynamicDepthwiseConvolution2DLayerCPU.h
        training/layers/basic/impl/DynamicDepthwiseConvolution2DLayerGPU.cpp
        training/layers/basic/impl/DynamicDepthwiseConvolution2DLayerGPU.h
        training/layers/basic/impl/BatchExpanderLayerCPU.cpp
        training/layers/basic/impl/ElementWiseCompareLayerGPU.cpp
        training/layers/basic/impl/TileLayerGPU.h
        training/layers/basic/impl/ReverseLayerCPU.cpp
        training/layers/basic/impl/ReshapeLayerCPU.h
        training/layers/basic/impl/BatchExpanderLayerCPU.h
        training/layers/basic/impl/ReshapeLayerGPU.h
        training/layers/basic/impl/NonZeroMaskLayerCPU.h
        training/layers/basic/impl/RoundLayerGPU.h
        training/layers/basic/impl/BatchExpanderLayerGPU.cpp
        training/layers/basic/impl/ReshapeLayerCPU.cpp
        training/layers/basic/impl/ElementWiseCompareLayerCPU.h
        training/layers/basic/impl/PositionalEncodingCPU.h
        training/layers/basic/impl/NonZeroMaskLayerGPU.cpp
        training/layers/basic/impl/RoundLayerCPU.cpp
        training/layers/basic/impl/NonZeroMaskLayerCPU.cpp
        training/layers/basic/impl/TileLayerCPU.cpp
        training/layers/basic/impl/ReverseLayerGPU.h
        training/layers/basic/impl/ReverseLayerCPU.h
        training/layers/basic/impl/ScaleLayerImpl.cpp
        training/layers/basic/impl/BatchExpanderLayerGPU.h
        training/layers/basic/impl/RoundLayerCPU.h
        training/layers/basic/impl/ElementWiseCompareLayerCPU.cpp
        training/layers/basic/impl/PositionalEncodingGPU.h
        training/layers/basic/impl/ReshapeLayerGPU.cpp
        training/layers/basic/impl/RoundLayerGPU.cpp
        training/layers/basic/impl/ScaleLayerImpl.h
        training/layers/basic/impl/TileLayerGPU.cpp
        training/layers/basic/impl/PositionalEncodingGPU.cpp
        training/layers/basic/impl/NonZeroMaskLayerGPU.h
        training/layers/basic/impl/ReverseLayerGPU.cpp
        training/layers/basic/impl/TileLayerCPU.h
        training/layers/basic/impl/PositionalEncodingCPU.cpp
        training/layers/basic/impl/ElementWiseCompareLayerGPU.h
        training/layers/basic/impl/MaskedFillLayerCPU.cpp
        training/layers/basic/impl/MaskedFillLayerCPU.h
        training/layers/basic/impl/LabelSmoothingCPU.cpp
        training/layers/basic/impl/LabelSmoothingCPU.h
        training/layers/basic/impl/ExpLayerCPU.cpp
        training/layers/basic/impl/ExpLayerCPU.h
        training/layers/basic/impl/ExpLayerGPU.cpp
        training/layers/basic/impl/ExpLayerGPU.h
        training/layers/basic/impl/SlicerLayerCPU.cpp
        training/layers/basic/impl/SlicerLayerCPU.h
        training/layers/basic/impl/SlicerLayerGPU.cpp
        training/layers/basic/impl/SlicerLayerGPU.h
        training/layers/basic/impl/ConcatenationLayerCPU.cpp
        training/layers/basic/impl/ConcatenationLayerCPU.h
        training/layers/basic/impl/ConcatenationLayerGPU.cpp
        training/layers/basic/impl/ConcatenationLayerGPU.h
        training/layers/basic/impl/CumSumLayerCPU.cpp
        training/layers/basic/impl/CumSumLayerCPU.h
        training/layers/basic/impl/CumSumLayerGPU.cpp
        training/layers/basic/impl/CumSumLayerGPU.h
        training/layers/basic/impl/ClampLayerCPU.cpp
        training/layers/basic/impl/ClampLayerCPU.h
        training/layers/basic/impl/ClampLayerGPU.cpp
        training/layers/basic/impl/ClampLayerGPU.h
        training/layers/basic/impl/SqrtLayerCPU.cpp
        training/layers/basic/impl/SqrtLayerCPU.h
        training/layers/basic/impl/SqrtLayerGPU.cpp
        training/layers/basic/impl/SqrtLayerGPU.h
        training/layers/basic/impl/RSqrtLayerCPU.cpp
        training/layers/basic/impl/RSqrtLayerCPU.h
        training/layers/basic/impl/RSqrtLayerGPU.cpp
        training/layers/basic/impl/RSqrtLayerGPU.h
        training/layers/basic/impl/SquareLayerCPU.cpp
        training/layers/basic/impl/SquareLayerCPU.h
        training/layers/basic/impl/SquareLayerGPU.cpp
        training/layers/basic/impl/SquareLayerGPU.h
        training/layers/basic/impl/LogLayerCPU.cpp
        training/layers/basic/impl/LogLayerCPU.h
        training/layers/basic/impl/LogLayerGPU.cpp
        training/layers/basic/impl/LogLayerGPU.h
        training/layers/basic/impl/FixedBiasLayerCPU.cpp
        training/layers/basic/impl/FixedBiasLayerCPU.h
        training/layers/basic/impl/FixedBiasLayerGPU.cpp
        training/layers/basic/impl/FixedBiasLayerGPU.h
        training/layers/basic/impl/L2NormLayerCPU.cpp
        training/layers/basic/impl/L2NormLayerCPU.h
        training/layers/basic/impl/L2SquaredNormLayerCPU.cpp
        training/layers/basic/impl/L2SquaredNormLayerCPU.h
        training/layers/basic/impl/RandomTensorLayerCPU.cpp
        training/layers/basic/impl/RandomTensorLayerCPU.h
        training/layers/basic/impl/ReduceExtremumLayerCPU.cpp
        training/layers/basic/impl/ReduceExtremumLayerCPU.h
        training/layers/basic/impl/ReduceArithmeticLayerCPU.cpp
        training/layers/basic/impl/ReduceArithmeticLayerCPU.h
        training/layers/basic/impl/ReduceArithmeticLayerGPU.cpp
        training/layers/basic/impl/ReduceArithmeticLayerGPU.h
        training/layers/basic/impl/SplitterLayerCPU.cpp
        training/layers/basic/impl/SplitterLayerCPU.h
        training/layers/basic/impl/SplitterLayerGPU.cpp
        training/layers/basic/impl/SplitterLayerGPU.h
        training/layers/basic/impl/TransposeLayerCPU.cpp
        training/layers/basic/impl/TransposeLayerCPU.h
        training/layers/basic/impl/TransposeLayerGPU.cpp
        training/layers/basic/impl/TransposeLayerGPU.h
        training/layers/basic/impl/TensorLayerCPU.cpp
        training/layers/basic/impl/TensorLayerCPU.h
        training/layers/basic/impl/TensorLayerGPU.cpp
        training/layers/basic/impl/TensorLayerGPU.h
        training/layers/basic/impl/SelectLayerCPU.cpp
        training/layers/basic/impl/SelectLayerCPU.h
        training/layers/basic/impl/SelectLayerGPU.cpp
        training/layers/basic/impl/SelectLayerGPU.h
        training/layers/basic/impl/RandomSelectLayerCPU.cpp
        training/layers/basic/impl/RandomSelectLayerCPU.h
        training/layers/basic/impl/RandomSelectLayerGPU.cpp
        training/layers/basic/impl/RandomSelectLayerGPU.h
        training/layers/basic/impl/MatMulLayerCPU.cpp
        training/layers/basic/impl/MatMulLayerCPU.h
        training/layers/basic/impl/MatMulLayerGPU.cpp
        training/layers/basic/impl/MatMulLayerGPU.h
        training/layers/basic/impl/LossWrapperHelperLayerCPU.cpp
        training/layers/basic/impl/LossWrapperHelperLayerCPU.h
        training/layers/basic/impl/LossWrapperHelperLayerGPU.cpp
        training/layers/basic/impl/LossWrapperHelperLayerGPU.h
        training/layers/basic/impl/ElementWiseSubLayerCPU.cpp
        training/layers/basic/impl/ElementWiseSubLayerCPU.h
        training/layers/basic/impl/ElementWiseSubLayerGPU.cpp
        training/layers/basic/impl/ElementWiseSubLayerGPU.h
        training/layers/basic/impl/ElementWiseSumLayerCPU.cpp
        training/layers/basic/impl/ElementWiseSumLayerCPU.h
        training/layers/basic/impl/ElementWiseSumLayerGPU.cpp
        training/layers/basic/impl/ElementWiseSumLayerGPU.h
        training/layers/basic/impl/ElementWiseDivLayerCPU.cpp
        training/layers/basic/impl/ElementWiseDivLayerCPU.h
        training/layers/basic/impl/ElementWiseDivLayerGPU.cpp
        training/layers/basic/impl/ElementWiseDivLayerGPU.h
        training/layers/basic/impl/ElementWiseMulLayerCPU.cpp
        training/layers/basic/impl/ElementWiseMulLayerCPU.h
        training/layers/basic/impl/ElementWiseMulLayerGPU.cpp
        training/layers/basic/impl/ElementWiseMulLayerGPU.h
        training/layers/basic/impl/DropoutLayerCPU.cpp
        training/layers/basic/impl/DropoutLayerCPU.h
        training/layers/basic/impl/DropoutLayerGPU.cpp
        training/layers/basic/impl/DropoutLayerGPU.h
        training/layers/basic/MatMulLayer.cpp
        training/layers/basic/L2SquaredNormLayer.cpp
        training/layers/basic/ElementWiseCompareLayer.cpp
        training/layers/basic/LabelSmoothing.cpp
        training/layers/basic/ReduceNonZeroLayer.cpp
        training/layers/basic/SplitterLayer.h
        training/layers/basic/ConvertPrecisionLayer.cpp
        training/layers/basic/ConvertPrecisionLayer.h
        training/layers/basic/ClampLayer.cpp
        training/layers/basic/SelectLayer.h
        training/layers/basic/ReverseLayer.h
        training/layers/basic/SlicerLayer.cpp
        training/layers/basic/ElementWiseCompareLayer.h
        training/layers/basic/ElementWiseSubLayer.h
        training/layers/basic/trainable/TransposedConvolution1DLayer.h
        training/layers/basic/trainable/Batchnorm.cpp
        training/layers/basic/trainable/Convolution1DLayer.cpp
        training/layers/basic/trainable/impl/LinearLayerImpl.cpp
        training/layers/basic/trainable/impl/BatchnormGPU.h
        training/layers/basic/trainable/impl/Convolution1DLayerCPU.cpp
        training/layers/basic/trainable/impl/Convolution1DLayerGPU.h
        training/layers/basic/trainable/impl/Convolution2DLayerCPU.h
        training/layers/basic/trainable/impl/BatchnormGPU.cpp
        training/layers/basic/trainable/impl/ConvolutionDepthwiseLayerCPU.cpp
        training/layers/basic/trainable/impl/ConvolutionDepthwiseLayerCPU.h
        training/layers/basic/trainable/impl/ConvolutionDepthwiseLayerGPU.cpp
        training/layers/basic/trainable/impl/ConvolutionDepthwiseLayerGPU.h
        training/layers/basic/trainable/impl/BatchnormCPU.cpp
        training/layers/basic/trainable/impl/BatchnormCPU.h
        training/layers/basic/trainable/impl/EmbeddingCPU.cpp
        training/layers/basic/trainable/impl/EmbeddingCPU.h
        training/layers/basic/trainable/impl/LayerNormCPU.cpp
        training/layers/basic/trainable/impl/LayerNormCPU.h
        training/layers/basic/trainable/impl/LayerNorm2dCPU.cpp
        training/layers/basic/trainable/impl/LayerNorm2dCPU.h
        training/layers/basic/trainable/impl/Convolution1DLayerCPU.h
        training/layers/basic/trainable/impl/Convolution1DLayerGPU.cpp
        training/layers/basic/trainable/impl/Convolution2DLayerCPU.cpp
        training/layers/basic/trainable/impl/LinearLayerImpl.h
        training/layers/basic/trainable/impl/LinearLayerCPUFP32Master.cpp
        training/layers/basic/trainable/impl/LinearLayerCPUFP32Master.h
        training/layers/basic/trainable/impl/LinearLayerCPUFP32.cpp
        training/layers/basic/trainable/impl/LinearLayerCPUFP32.h
        training/layers/basic/trainable/impl/LinearLayerCPUFP16.h
        training/layers/basic/trainable/impl/LinearLayerCPUFP16.cpp
        training/layers/basic/trainable/TransposedConvolution2DLayer.cpp
        training/layers/basic/trainable/LayerNorm.cpp
        training/layers/basic/trainable/LayerNorm2D.cpp
        training/layers/basic/trainable/TransposedConvolution1DLayer.cpp
        training/layers/basic/trainable/Embedding.h
        training/layers/basic/trainable/ConvolutionDepthwiseLayer.h
        training/layers/basic/trainable/Convolution1DLayer.h
        training/layers/basic/trainable/LinearLayer.cpp
        training/layers/basic/trainable/LinearLayer.h
        training/layers/basic/trainable/LayerNorm.h
        training/layers/basic/trainable/LayerNorm2D.h
        training/layers/basic/trainable/Batchnorm.h
        training/layers/basic/trainable/Convolution2DLayer.h
        training/layers/basic/trainable/TransposedConvolution2DLayer.h
        training/layers/basic/trainable/Embedding.cpp
        training/layers/basic/trainable/ConvolutionDepthwiseLayer.cpp
        training/layers/basic/trainable/Convolution2DLayer.cpp
        training/layers/basic/LogLayer.h
        training/layers/basic/ElementWiseMaxLayer.h
        training/layers/basic/TileLayer.h
        training/layers/basic/LabelSmoothing.h
        training/layers/basic/ReduceArithmeticLayer.cpp
        training/layers/basic/LogLayer.cpp
        training/layers/basic/ElementWiseMinLayer.h
        training/layers/basic/SelectLayer.cpp
        training/layers/basic/L2NormLayer.cpp
        training/layers/basic/SquareLayer.h
        training/layers/basic/LossWrapperHelperLayer.h
        training/layers/basic/SqrtLayer.cpp
        training/layers/basic/FakeQuantLayer.h
        training/layers/basic/ArgMaxLayer.h
        training/layers/basic/ElementWiseSumLayer.h
        training/layers/basic/RSqrtLayer.cpp
        training/layers/basic/GlobalAveragePoolLayer.cpp
        training/layers/basic/DataLayer.cpp
        training/layers/basic/ReduceSumLayer.cpp
        training/layers/basic/CumSumLayer.cpp
        training/layers/basic/TransposeLayer.h
        training/layers/basic/ReduceBatchMeanLayer.h
        training/layers/basic/ReverseLayer.cpp
        training/layers/basic/ElementWiseMulLayer.cpp
        training/layers/basic/DynamicDepthwiseConvolution2DLayer.h
        training/layers/basic/ReduceMinLayer.h
        training/layers/basic/TileLayer.cpp
        training/layers/basic/ElementWiseSumLayer.cpp
        training/layers/basic/BatchExpanderLayer.h
        training/layers/basic/ReduceExtremumLayer.cpp
        training/layers/basic/AveragePoolLayer.h
        training/layers/basic/L2SquaredNormLayer.h
        training/layers/basic/MaskedFillLayer.cpp
        training/layers/basic/ReduceExtremumLayer.h
        training/layers/basic/ReduceNonZeroLayer.h
        training/layers/basic/ReduceMaxLayer.h
        training/layers/basic/MaxPoolLayer.cpp
        training/layers/basic/ReduceSumLayer.h
        training/layers/basic/ReduceArithmeticLayer.h
        training/layers/basic/SplitterLayer.cpp
        training/layers/basic/ReduceStdLayer.cpp
        training/layers/basic/SquareLayer.cpp
        training/layers/basic/L2NormLayer.h
        training/layers/basic/IndexFillLayer.cpp
        training/layers/basic/ReshapeLayer.h
        training/layers/basic/ElementWiseSubLayer.cpp
        training/layers/basic/PaddingLayer.h
        training/layers/basic/ReduceMeanLayer.h
        training/layers/basic/ElementWiseDivLayer.h
        training/layers/basic/DataLayer.h
        training/layers/basic/MaskedFillLayer.h
        training/layers/basic/DynamicDepthwiseConvolution2DLayer.cpp
        training/layers/basic/RepeatInterleaveLayer.cpp
        training/layers/basic/FixedBiasLayer.cpp
        training/layers/basic/ReduceStdLayer.h
        training/layers/basic/FixedBiasLayer.h
        training/layers/basic/TensorLayer.cpp
        training/layers/basic/ElementWiseMulLayer.h
        training/layers/basic/PaddingLayer.cpp
        training/layers/basic/ConcatenationLayer.cpp
        training/layers/basic/ArgMinLayer.h
        training/layers/basic/ElementWiseExtremumLayer.h
        training/layers/basic/TensorLayer.h
        training/layers/basic/SlicerLayer.h
        training/layers/basic/ElementWiseDivLayer.cpp
        training/layers/basic/IndexFillLayer.h
        training/layers/basic/RSqrtLayer.h
        training/layers/basic/TransposeLayer.cpp
        training/layers/basic/RollLayer.h
        training/layers/basic/RandomSelectLayer.h
        training/layers/basic/RandomSelectLayer.cpp
        training/layers/basic/CumSumLayer.h
        training/layers/basic/DropoutLayer.cpp
        training/layers/basic/NonZeroMaskLayer.h
        training/layers/basic/RandomChoiceLayer.cpp
        training/layers/basic/RollLayer.cpp
        training/layers/basic/RepeatInterleaveLayer.h
        training/layers/basic/ReduceBatchMeanLayer.cpp
        training/layers/basic/LossWrapperHelperLayer.cpp
        training/layers/basic/AveragePoolLayer.cpp
        training/layers/basic/PositionalEncoding.h
        training/layers/MetaLayer.h
        training/layers/composite/DynamicConvolutionAttentionLayer.cpp
        training/layers/composite/Transformer.cpp
        training/layers/composite/TacotronDecoder.cpp
        training/layers/composite/MultiHeadAttention.h
        training/layers/composite/BahdanauMonotonicAttentionLayer.cpp
        training/layers/composite/meta/SequentialMetaLayer.h
        training/layers/composite/meta/SequentialMetaLayer.cpp
        training/layers/composite/meta/RecurrentMetaLayer.h
        training/layers/composite/meta/RecurrentMetaLayer.cpp
        training/layers/composite/meta/StackedMetaLayer.cpp
        training/layers/composite/meta/StackedMetaLayer.h
        training/layers/composite/TacotronDecoder.h
        training/layers/composite/BahdanauMonotonicAttentionLayer.h
        training/layers/composite/AdditiveAttentionLayer.h
        training/layers/composite/TacotronModel.cpp
        training/layers/composite/BahdanauMonotonicAttentionInternalLayers.h
        training/layers/composite/LocationSensitiveAttentionInternalLayers.h
        training/layers/composite/rnn/BidirectionalLSTMFunc.h
        training/layers/composite/rnn/impl/ZeroOutputLayerCPU.h
        training/layers/composite/rnn/impl/ZeroOutputLayerCPU.cpp
        training/layers/composite/rnn/impl/ZeroOutputLayerGPU.h
        training/layers/composite/rnn/impl/ZeroOutputLayerGPU.cpp
        training/layers/composite/rnn/impl/GRUFusedGatesCalcLayerCPU.h
        training/layers/composite/rnn/impl/GRUFusedGatesCalcLayerCPU.cpp
        training/layers/composite/rnn/ZoneoutLayer.h
        training/layers/composite/rnn/ZoneoutLayer.cpp
        training/layers/composite/rnn/ZeroOutputLayer.cpp
        training/layers/composite/rnn/LSTMCellLayer.h
        training/layers/composite/rnn/LSTMCellLayer.cpp
        training/layers/composite/rnn/BidirectionalLSTMFunc.cpp
        training/layers/composite/rnn/LSTMLayer.h
        training/layers/composite/rnn/LSTMLayer.cpp
        training/layers/composite/rnn/ZeroOutputLayer.h
        training/layers/composite/rnn/GRUCellLayer.h
        training/layers/composite/rnn/GRUCellLayer.cpp
        training/layers/composite/rnn/GRULayer.h
        training/layers/composite/rnn/GRULayer.cpp
        training/layers/composite/rnn/GRUFusedGatesCalcLayer.h
        training/layers/composite/rnn/GRUFusedGatesCalcLayer.cpp
        training/layers/composite/AttentionLayer.cpp
        training/layers/composite/BERT.cpp
        training/layers/composite/GaussianUpsamplingLayer.cpp
        training/layers/composite/GaussianUpsamplingLayer.h
        training/layers/composite/Transformer.h
        training/layers/composite/TacotronModel.h
        training/layers/composite/AttentionLayer.h
        training/layers/composite/MultiHeadAttention.cpp
        training/layers/composite/AdditiveAttentionLayer.cpp
        training/layers/composite/BERT.h
        training/layers/composite/LocationSensitiveAttentionLayer.h
        training/layers/composite/tacotron/MaskedCrossEntropy.cpp
        training/layers/composite/tacotron/TargetsReductionLayer.h
        training/layers/composite/tacotron/MaskedLoss.h
        training/layers/composite/tacotron/PostNet.h
        training/layers/composite/tacotron/MaskedCrossEntropy.h
        training/layers/composite/tacotron/SequenceLoss.cpp
        training/layers/composite/tacotron/impl/TacotronDataInitializationLayerGPU.h
        training/layers/composite/tacotron/impl/SequenceMaskLayerCPU.cpp
        training/layers/composite/tacotron/impl/SequenceMaskLayerGPU.cpp
        training/layers/composite/tacotron/impl/GaussianUpsamplingDistributionLayerGPU.cpp
        training/layers/composite/tacotron/impl/TargetsReductionLayerGPU.cpp
        training/layers/composite/tacotron/impl/TargetsReductionLayerGPU.h
        training/layers/composite/tacotron/impl/TacotronDataInitializationLayerCPU.cpp
        training/layers/composite/tacotron/impl/TacotronDataInitializationLayerCPU.h
        training/layers/composite/tacotron/impl/GaussianUpsamplingDistributionLayerCPU.cpp
        training/layers/composite/tacotron/impl/GaussianUpsamplingDistributionLayerCPU.h
        training/layers/composite/tacotron/impl/SequenceMaskLayerGPU.h
        training/layers/composite/tacotron/impl/GaussianUpsamplingDistributionLayerGPU.h
        training/layers/composite/tacotron/impl/SequenceMaskLayerCPU.h
        training/layers/composite/tacotron/impl/TargetsReductionLayerCPU.h
        training/layers/composite/tacotron/impl/TargetsReductionLayerCPU.cpp
        training/layers/composite/tacotron/impl/TacotronDataInitializationLayerGPU.cpp
        training/layers/composite/tacotron/TacotronDataInitializationLayer.cpp
        training/layers/composite/tacotron/SequenceMaskLayer.h
        training/layers/composite/tacotron/DurationPredictor.cpp
        training/layers/composite/tacotron/Miscellaneous.h
        training/layers/composite/tacotron/SequenceLoss.h
        training/layers/composite/tacotron/TacotronLoss.cpp
        training/layers/composite/tacotron/SequenceMaskLayer.cpp
        training/layers/composite/tacotron/PostNet.cpp
        training/layers/composite/tacotron/TacotronDecoderRNN.h
        training/layers/composite/tacotron/TacotronDataInitializationLayer.h
        training/layers/composite/tacotron/TargetsReductionLayer.cpp
        training/layers/composite/tacotron/TacotronDecoderCell.cpp
        training/layers/composite/tacotron/TacotronDecoderRNN.cpp
        training/layers/composite/tacotron/MaskedLoss.cpp
        training/layers/composite/tacotron/GaussianUpsamplingDistributionLayer.h
        training/layers/composite/tacotron/TacotronLoss.h
        training/layers/composite/tacotron/TacotronDecoderCell.h
        training/layers/composite/tacotron/Miscellaneous.cpp
        training/layers/composite/tacotron/DurationPredictor.h
        training/layers/composite/tacotron/GaussianUpsamplingDistributionLayer.cpp
        training/layers/composite/LocationSensitiveAttentionLayer.cpp
        training/layers/composite/DynamicConvolutionAttentionInternalLayers.h
        training/layers/composite/AttentionMaskCreatorLayer.h
        training/layers/composite/DynamicConvolutionAttentionLayer.h
        training/layers/BasicImpl.h
        training/layers/TrainableLayer.cpp
        training/layers/BasicLayer.h
        training/loss/scaling/ScalingStrategy.h
        training/loss/SigmoidCrossEntropyLoss.cpp
        training/loss/L1Loss.h
        training/loss/DivisorLossHelperLayer.h
        training/loss/CrossEntropyLoss.h
        training/loss/CrossEntropyLoss.cpp
        training/loss/NegativeLogLikelihoodLoss.cpp
        training/loss/SoftmaxCrossEntropyLoss.cpp
        training/loss/L1Loss.cpp
        training/loss/MSELoss.h
        training/loss/SoftmaxCrossEntropyLoss.h
        training/loss/SigmoidCrossEntropyLoss.h
        training/loss/MSELoss.cpp
        training/loss/KLDivLoss.h
        training/loss/KLDivLoss.cpp
        training/loss/NegativeLogLikelihoodLoss.h
        training/loss/LossWrapper.h
        training/loss/BinaryCrossEntropyLoss.cpp
        training/loss/BinaryCrossEntropyLoss.h
        training/loss/impl/L1LossCPU.cpp
        training/loss/impl/L1LossCPU.h
        training/loss/impl/L1LossGPU.cpp
        training/loss/impl/L1LossGPU.h
        training/loss/impl/MSELossCPU.cpp
        training/loss/impl/MSELossCPU.h
        training/loss/impl/MSELossGPU.cpp
        training/loss/impl/MSELossGPU.h
        training/loss/impl/DivisorLossHelperLayerCPU.cpp
        training/loss/impl/DivisorLossHelperLayerCPU.h
        training/loss/impl/DivisorLossHelperLayerGPU.cpp
        training/loss/impl/DivisorLossHelperLayerGPU.h
        training/version/Version.h
        )

if (RAUL_BUILD_C_API)
    target_sources(Raul PRIVATE
            training/api/APIHyperparams.h
            training/api/API.cpp
            training/api/API.h
            training/api/lowlevel/APIDefinitions.h
            training/api/lowlevel/APIChecks.h
            )
endif ()
