for file in *
    do
        if [ "${file##*.}"x = "cl"x ];then
             if [[ "${file}" == gemm_tn.cl ]];then
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_41.bin  --options=\"${copt} -D LM=4 -D LN=1 -D UN=0 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_42.bin  --options=\"${copt} -D LM=4 -D LN=2 -D UN=1 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_43.bin  --options=\"${copt} -D LM=4 -D LN=3 -D UN=2 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_44.bin  --options=\"${copt} -D LM=4 -D LN=4 -D UN=3 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_45.bin  --options=\"${copt} -D LM=4 -D LN=5 -D UN=4 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_46.bin  --options=\"${copt} -D LM=4 -D LN=6 -D UN=5 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_47.bin  --options=\"${copt} -D LM=4 -D LN=7 -D UN=6 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_48.bin  --options=\"${copt} -D LM=4 -D LN=8 -D UN=7 -DUSE_NCWHC4\"

                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_81.bin  --options=\"${copt} -D LM=8 -D LN=1 -D UN=0 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_82.bin  --options=\"${copt} -D LM=8 -D LN=2 -D UN=1 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_83.bin  --options=\"${copt} -D LM=8 -D LN=3 -D UN=2 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_84.bin  --options=\"${copt} -D LM=8 -D LN=4 -D UN=3 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_85.bin  --options=\"${copt} -D LM=8 -D LN=5 -D UN=4 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_86.bin  --options=\"${copt} -D LM=8 -D LN=6 -D UN=5 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_87.bin  --options=\"${copt} -D LM=8 -D LN=7 -D UN=6 -DUSE_NCWHC4\"
                echo ./gcl_binary --input=$file --output=${file%.*}_ncwhc4_88.bin  --options=\"${copt} -D LM=8 -D LN=8 -D UN=7 -DUSE_NCWHC4\"

                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_41.bin  --options=\"${copt} -D LM=4 -D LN=1 -D UN=0 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_42.bin  --options=\"${copt} -D LM=4 -D LN=2 -D UN=1 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_43.bin  --options=\"${copt} -D LM=4 -D LN=3 -D UN=2 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_44.bin  --options=\"${copt} -D LM=4 -D LN=4 -D UN=3 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_45.bin  --options=\"${copt} -D LM=4 -D LN=5 -D UN=4 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_46.bin  --options=\"${copt} -D LM=4 -D LN=6 -D UN=5 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_47.bin  --options=\"${copt} -D LM=4 -D LN=7 -D UN=6 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_48.bin  --options=\"${copt} -D LM=4 -D LN=8 -D UN=7 -DUSE_NCWHC4 -DUSE_RELU\"

                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_81.bin  --options=\"${copt} -D LM=8 -D LN=1 -D UN=0 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_82.bin  --options=\"${copt} -D LM=8 -D LN=2 -D UN=1 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_83.bin  --options=\"${copt} -D LM=8 -D LN=3 -D UN=2 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_84.bin  --options=\"${copt} -D LM=8 -D LN=4 -D UN=3 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_85.bin  --options=\"${copt} -D LM=8 -D LN=5 -D UN=4 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_86.bin  --options=\"${copt} -D LM=8 -D LN=6 -D UN=5 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_87.bin  --options=\"${copt} -D LM=8 -D LN=7 -D UN=6 -DUSE_NCWHC4 -DUSE_RELU\"
                echo ./gcl_binary --input=$file --output=${file%.*}_relu_ncwhc4_88.bin  --options=\"${copt} -D LM=8 -D LN=8 -D UN=7 -DUSE_NCWHC4 -DUSE_RELU\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_13.bin  --options=\"${copt} -D LM=1 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_14.bin  --options=\"${copt} -D LM=1 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_15.bin  --options=\"${copt} -D LM=1 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_16.bin  --options=\"${copt} -D LM=1 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_17.bin  --options=\"${copt} -D LM=1 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_18.bin  --options=\"${copt} -D LM=1 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_22.bin  --options=\"${copt} -D LM=2 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_23.bin  --options=\"${copt} -D LM=2 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_24.bin  --options=\"${copt} -D LM=2 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_25.bin  --options=\"${copt} -D LM=2 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_26.bin  --options=\"${copt} -D LM=2 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_27.bin  --options=\"${copt} -D LM=2 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_28.bin  --options=\"${copt} -D LM=2 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_31.bin  --options=\"${copt} -D LM=3 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_32.bin  --options=\"${copt} -D LM=3 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_33.bin  --options=\"${copt} -D LM=3 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_34.bin  --options=\"${copt} -D LM=3 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_35.bin  --options=\"${copt} -D LM=3 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_36.bin  --options=\"${copt} -D LM=3 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_37.bin  --options=\"${copt} -D LM=3 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_38.bin  --options=\"${copt} -D LM=3 -D LN=8 -D NO_BIAS\"
                
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_41.bin  --options=\"${copt} -D LM=4 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_42.bin  --options=\"${copt} -D LM=4 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_43.bin  --options=\"${copt} -D LM=4 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_44.bin  --options=\"${copt} -D LM=4 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_45.bin  --options=\"${copt} -D LM=4 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_46.bin  --options=\"${copt} -D LM=4 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_47.bin  --options=\"${copt} -D LM=4 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_48.bin  --options=\"${copt} -D LM=4 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_51.bin  --options=\"${copt} -D LM=5 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_52.bin  --options=\"${copt} -D LM=5 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_53.bin  --options=\"${copt} -D LM=5 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_54.bin  --options=\"${copt} -D LM=5 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_55.bin  --options=\"${copt} -D LM=5 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_56.bin  --options=\"${copt} -D LM=5 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_57.bin  --options=\"${copt} -D LM=5 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_58.bin  --options=\"${copt} -D LM=5 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_61.bin  --options=\"${copt} -D LM=6 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_62.bin  --options=\"${copt} -D LM=6 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_63.bin  --options=\"${copt} -D LM=6 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_64.bin  --options=\"${copt} -D LM=6 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_65.bin  --options=\"${copt} -D LM=6 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_66.bin  --options=\"${copt} -D LM=6 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_67.bin  --options=\"${copt} -D LM=6 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_68.bin  --options=\"${copt} -D LM=6 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_71.bin  --options=\"${copt} -D LM=7 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_72.bin  --options=\"${copt} -D LM=7 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_73.bin  --options=\"${copt} -D LM=7 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_74.bin  --options=\"${copt} -D LM=7 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_75.bin  --options=\"${copt} -D LM=7 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_76.bin  --options=\"${copt} -D LM=7 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_77.bin  --options=\"${copt} -D LM=7 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_78.bin  --options=\"${copt} -D LM=7 -D LN=8 -D NO_BIAS\"

                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_81.bin  --options=\"${copt} -D LM=8 -D LN=1 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_82.bin  --options=\"${copt} -D LM=8 -D LN=2 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_83.bin  --options=\"${copt} -D LM=8 -D LN=3 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_84.bin  --options=\"${copt} -D LM=8 -D LN=4 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_85.bin  --options=\"${copt} -D LM=8 -D LN=5 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_86.bin  --options=\"${copt} -D LM=8 -D LN=6 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_87.bin  --options=\"${copt} -D LM=8 -D LN=7 -D NO_BIAS\"
                echo ./gcl_binary --input=$file --output=${file%.*}_nobias_88.bin  --options=\"${copt} -D LM=8 -D LN=8 -D NO_BIAS\"
             fi
        fi
    done



