Bolt: inference/engine/api/c/bolt.h File Reference
bolt.h File Reference
C API Document.
Typedefs
typedef void * ModelHandle
typedef void * ResultHandle
Enumerations
enum AFFINITY_TYPE { CPU_HIGH_PERFORMANCE = 0, CPU_LOW_POWER = 1, GPU = 2 }
enum DEVICE_TYPE {
CPU_SERIAL = 0, CPU_ARM_V7 = 1, CPU_ARM_V8 = 2, CPU_ARM_A55 = 3,
CPU_ARM_A76 = 4, CPU_X86_AVX2 = 5, CPU_X86_AVX512 = 6, GPU_MALI = 10,
GPU_QUALCOMM = 11
}
enum DATA_TYPE { FP_32 = 0, FP_16 = 1, INT_32 = 2, UINT_32 = 3 }
enum DATA_FORMAT {
NCHW = 0, NHWC = 1, NCHWC8 = 2, MTK = 3,
NORMAL = 4, NCHWC4 = 5
}
Functions
const char *const * GetDataTypeString ()
const char *const * GetDataFormatString ()
ModelHandle CreateModel (const char *modelPath, AFFINITY_TYPE affinity, const char *algorithmMapPath)
create model from file
int GetNumInputsFromModel (ModelHandle ih)
get the number of model input from ModelHandle
void GetInputDataInfoFromModel (ModelHandle ih, int num_inputs, char **name, int *n, int *c, int *h, int *w, DATA_TYPE *dt, DATA_FORMAT *df)
get input data info set in model handle, which is read from .bolt
void PrepareModel (ModelHandle ih, const int num_inputs, const char **name, const int *n, const int *c, const int *h, const int *w, const DATA_TYPE *dt, const DATA_FORMAT *df)
complete model inference engine prepare
ResultHandle AllocAllResultHandle (ModelHandle ih)
malloc result data memory
void RunModel (ModelHandle ih, ResultHandle ir, int num_inputs, const char **name, void **data)
inference result from input
int GetNumOutputsFromResultHandle (ResultHandle ir)
get the number of model output from ResultHandle
void GetOutputDataInfoFromResultHandle (ResultHandle ir, int num_outputs, char **outputNames, int *n, int *c, int *h, int *w, DATA_TYPE *dt, DATA_FORMAT *df)
get output Data info from ResultHandle
void GetOutputDataFromResultHandle (ResultHandle ir, int num_outputs, void **data)
get output data from ResultHandle, default to pass value of output ptr,
void FreeResultHandle (ResultHandle ir)
free result data memory
void DestroyModel (ModelHandle ih)
destroy model
void GetGpuDeviceName (char *gpuDeviceName)
ModelHandle CreateModelWithFileStream (const char *modelFileStream, AFFINITY_TYPE affinity, const char *algorithmMapFileStream)
create model from file stream Other info is the same with CreateModel
void GetInputDataInfoFromModel5D (ModelHandle ih, int num_inputs, char **name, int *n, int *c, int *t, int *h, int *w, DATA_TYPE *dt, DATA_FORMAT *df)
get input Data info set in model handle, when input data is 5d input dims (n,c,t,h,w) other info please reference GetInputDataInfoFromModel
void PrepareModel5D (ModelHandle ih, int num_input, const char **name, const int *n, const int *c, const int *t, const int *h, const int *w, const DATA_TYPE *dt_input, const DATA_FORMAT *df_input)
complete model inference engine prepare when input data dim is 5d input dims (n,c,t,h,w) other info please reference PrepareModel
void ResizeModelInput (ModelHandle ih, int num_inputs, const char **name, const int *n, const int *c, const int *h, const int *w, const DATA_TYPE *dt, const DATA_FORMAT *df)
resize model input size
ResultHandle AllocSpecificResultHandle (ModelHandle ih, int num_outputs, const char **name)
malloc result data memory according to user specification
ModelHandle CloneModel (ModelHandle ih)
clone model from a model
ResultHandle CloneResultHandle (ResultHandle ir)
clone result handle
void SetRuntimeDevice (ModelHandle ih, int cpu_id, DEVICE_TYPE device)
set process to run on specified CPU core
void SetRuntimeDeviceDynamic (ModelHandle ih)
set process cpu affinity according cpu average occupy
void SetNumThreads (int threads)
set parallel threads num
Detailed Description
C API Document.
Copyright
Copyright (C) 2019. Huawei Technologies Co., Ltd. All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file bolt.h.
Typedef Documentation
ModelHandle
typedef void* ModelHandle
inference pipeline handle
Definition at line 29 of file bolt.h.
ResultHandle
typedef void* ResultHandle
result data memory handle
Definition at line 32 of file bolt.h.
Enumeration Type Documentation
AFFINITY_TYPE
enum AFFINITY_TYPE
CPU affinity policy
Enumerator
CPU_HIGH_PERFORMANCE
performance is high priority(use big core)
CPU_LOW_POWER
power is high priority(use small core)
GPU
use GPU
Definition at line 35 of file bolt.h.
DATA_FORMAT
enum DATA_FORMAT
multi-dimension data format
Enumerator
NCHW
batch->channel->high->width data order
NHWC
batch->high->width->channel data order
NCHWC8
batch->channel/8->high->width->channel four element data order
MTK
batch->time->unit data order
NORMAL
batch->unit data order
NCHWC4
batch->channel/4->width->high->channel four element data order
Definition at line 70 of file bolt.h.
DATA_TYPE
enum DATA_TYPE
data precision
Enumerator
FP_32
32 bit float
FP_16
16 bit float
INT_32
32 bit integer
UINT_32
32 bit unsigned integer
Definition at line 55 of file bolt.h.
DEVICE_TYPE
enum DEVICE_TYPE
heterogeneous device type
Enumerator
CPU_SERIAL
CPU serial.
CPU_ARM_V7
ARMv7 CPU.
CPU_ARM_V8
ARMv8 CPU.
CPU_ARM_A55
ARM A55 CPU.
CPU_ARM_A76
ARM A76 CPU.
CPU_X86_AVX2
X86_64 AVX2 CPU.
CPU_X86_AVX512
X86_64 AVX512 CPU.
GPU_MALI
ARM MALI GPU.
GPU_QUALCOMM
ARM MALI GPU.
Definition at line 42 of file bolt.h.
Function Documentation
AllocAllResultHandle()
ResultHandle AllocAllResultHandle (ModelHandle ih)
malloc result data memory
Parameters
ih inference pipeline handle
Returns
result data memory handle
Referenced by GetDataFormatString().
AllocSpecificResultHandle()
ResultHandle AllocSpecificResultHandle (ModelHandle ih, int num_outputs, const char ** name)
malloc result data memory according to user specification
Parameters
ih inference pipeline handle
num_outputs the number of tensor that needed
name the array of tesor name that needed
Returns
result data memory handle
Referenced by GetDataFormatString().
CloneModel()
ModelHandle CloneModel (ModelHandle ih)
clone model from a model
Parameters
ih a inference pipeline handle pointer of a model
Returns
inference pipeline handle
Note
This function can not be called before PrepareModel. The model that being cloned can not be changed before all threads complete clone function.
ModelHandle handle = CreateModel(...);
PrepareModel(handle);
ModelHandle clone_handle = CloneModel(handle);
...
DestroyModel(handle);
DestroyModel(clone_handle);
Referenced by GetDataFormatString().
CloneResultHandle()
ResultHandle CloneResultHandle (ResultHandle ir)
clone result handle
Parameters
ir a result data handle
Returns
result data memory handle
Note
The result handle that being cloned can not be changed before all threads complete clone function.
Referenced by GetDataFormatString().
CreateModel()
ModelHandle CreateModel (const char * modelPath, AFFINITY_TYPE affinity, const char * algorithmMapPath)
create model from file
Parameters
modelPath model file path
affinity CPU affinity setting
algorithmMapPath the file path to save and load algorithm map file
Returns
inference pipeline handle
Note
destroy model when pipeline end
ModelHandle handle = CreateModel(...);
...
DestroyModel(handle);
algorithmMapPath is for GPU. If you don't need it, please set it NULL. If algorithmMapPath is set to a existed valid algorithm map file, inference will directly use it. If algorithmMapPath is not existed, inference will run algorithm tuning, which is usually time consuming. Inference will write algorithm tuning result to file.
If your input tensor size or model is changed, please delete the old algorithm map file. If any unexpected error happen, you can try to delete algorithm file and run it again.
Referenced by GetDataFormatString().
DestroyModel()
void DestroyModel (ModelHandle ih)
destroy model
Parameters
ih inference pipeline handle
Returns
Referenced by GetDataFormatString().
FreeResultHandle()
void FreeResultHandle (ResultHandle ir)
free result data memory
Parameters
ir result data memory handle
Returns
Referenced by GetDataFormatString().
GetDataFormatString()
const char* const* GetDataFormatString ()
Get DATA_FORMAT String
Definition at line 80 of file bolt.h.
References AllocAllResultHandle(), AllocSpecificResultHandle(), CloneModel(), CloneResultHandle(), CreateModel(), CreateModelWithFileStream(), DestroyModel(), FreeResultHandle(), GetGpuDeviceName(), GetInputDataInfoFromModel(), GetInputDataInfoFromModel5D(), GetNumInputsFromModel(), GetNumOutputsFromResultHandle(), GetOutputDataFromResultHandle(), GetOutputDataInfoFromResultHandle(), PrepareModel(), PrepareModel5D(), ResizeModelInput(), RunModel(), SetNumThreads(), SetRuntimeDevice(), and SetRuntimeDeviceDynamic().
GetDataTypeString()
const char* const* GetDataTypeString ()
Get DATA_TYPE String
Definition at line 63 of file bolt.h.
GetGpuDeviceName()
void GetGpuDeviceName (char * gpuDeviceName)
Copy current GPU device name to gpuDeviceName User need to alloc memory of gpuDeviceName used with CreateModelWithFileStream to help user choose algoFile
Referenced by GetDataFormatString().
GetInputDataInfoFromModel()
void GetInputDataInfoFromModel (ModelHandle ih, int num_inputs, char ** name, int * n, int * c, int * h, int * w, DATA_TYPE * dt, DATA_FORMAT * df)
get input data info set in model handle, which is read from .bolt
Parameters
ih inference pipeline handle
num_inputs the number of input
name the array of all input data's name
n the array of all input data's n dimension
c the array of all input data's c dimension
h the array of all input data's h dimension
w the array of all input data's w dimension
dt the array of all input data's data type
df the array of all input data's data format
Returns
Note
name/n/c/h/w/dt/df array space must be allocated before calling, the array length must be equal to num_inputs. each element of name must be allocated, the array length must be equal to 128.
Referenced by GetDataFormatString().
GetNumInputsFromModel()
int GetNumInputsFromModel (ModelHandle ih)
get the number of model input from ModelHandle
Parameters
ih inference pipeline handle
Returns
the number of input
Referenced by GetDataFormatString().
GetNumOutputsFromResultHandle()
int GetNumOutputsFromResultHandle (ResultHandle ir)
get the number of model output from ResultHandle
Parameters
ir result data memory handle
Returns
the number of output
Referenced by GetDataFormatString().
GetOutputDataFromResultHandle()
void GetOutputDataFromResultHandle (ResultHandle ir, int num_outputs, void ** data)
get output data from ResultHandle, default to pass value of output ptr,
Parameters
ir result data memory handle
num_outputs the number of output data
data the array of all output data's content
Returns
Referenced by GetDataFormatString().
GetOutputDataInfoFromResultHandle()
void GetOutputDataInfoFromResultHandle (ResultHandle ir, int num_outputs, char ** outputNames, int * n, int * c, int * h, int * w, DATA_TYPE * dt, DATA_FORMAT * df)
get output Data info from ResultHandle
Parameters
ir result data memory handle
num_outputs the number of output data
outputNames the array of all output data's name
n the array of all output data's n dimension
c the array of all output data's c dimension
h the array of all output data's h dimension
w the array of all output data's w dimension
dt the array of all output data's data type
df the array of all output data's data format
Returns
Note
name/n/c/h/w/dt/df array space must be allocated before calling, the array length must be equal to num_inputs. each element of name must be allocated, the array length must be equal to 128.
Referenced by GetDataFormatString().
PrepareModel()
void PrepareModel (ModelHandle ih, const int num_inputs, const char ** name, const int * n, const int * c, const int * h, const int * w, const DATA_TYPE * dt, const DATA_FORMAT * df)
complete model inference engine prepare
Parameters
ih model inference handle
num_inputs the number of input data
name the array of all input data's name in string format
n the array of all input data's n dimension
c the array of all input data's c dimension
h the array of all input data's h dimension
w the array of all input data's w dimension
dt the array of all input data's data type
df the array of all input data's data format
Returns
Note
name/n/c/h/w/dt/df array space must be allocated before calling, the array length must be equal to num_inputs. each element of name must be allocated, the array length must be equal to 128.
Referenced by GetDataFormatString().
ResizeModelInput()
void ResizeModelInput (ModelHandle ih, int num_inputs, const char ** name, const int * n, const int * c, const int * h, const int * w, const DATA_TYPE * dt, const DATA_FORMAT * df)
resize model input size
Parameters
ih model inference handle
num_inputs the number of input data
name the array of all input data's name in string format
n the array of all input data's n dimension
c the array of all input data's c dimension
h the array of all input data's h dimension
w the array of all input data's w dimension
dt the array of all input data's data type
df the array of all input data's data format
Returns
Note
name/n/c/h/w/dt/df array space must be allocated before calling, the array length must be equal to num_inputs. each element of name must be allocated, the array length must be equal to 128.
// model_resize must behind PrepareModel;
PrepareModel(...);
ResizeModelInput(...);
RunModel(...);
Referenced by GetDataFormatString().
RunModel()
void RunModel (ModelHandle ih, ResultHandle ir, int num_inputs, const char ** name, void ** data)
inference result from input
Parameters
ih inference pipeline handle
ir result data memory handle
num_inputs the number of input data
name the array of all input data's name
data the array of all input data
Returns
Referenced by GetDataFormatString().
SetNumThreads()
void SetNumThreads (int threads)
set parallel threads num
Parameters
threads number of threads
Note
This can only be used before RunModel. If you use it before PrepareModel, this will affect tmp buffer allocation. Then you are limited that next setting can not greater than before one. This setting is global to each inference threads.
Returns
Referenced by GetDataFormatString().
SetRuntimeDevice()
void SetRuntimeDevice (ModelHandle ih, int cpu_id, DEVICE_TYPE device)
set process to run on specified CPU core
Parameters
ih inference pipeline handle
cpu_id cpu core id(0, 1, 2...)
device cpu core architecture(ARM_A76)
Returns
Referenced by GetDataFormatString().
SetRuntimeDeviceDynamic()
void SetRuntimeDeviceDynamic (ModelHandle ih)
set process cpu affinity according cpu average occupy
Parameters
ih inference pipeline handle
Returns
Referenced by GetDataFormatString().